from pathlib import Path  # Preserve the official solver source and the exact local preprocessing correction.
import subprocess, requests, tarfile, io, json, hashlib, difflib  # Compile and audit the native solver without altering engineering parameters.
ROOT=Path(__file__).parent  # Keep the build separate from every historical numerical model.
def build():  # Activate native rotational coordinates already requested by physical connection equations.
    folder=ROOT/'runtime_joint';folder.mkdir(exist_ok=True);evidence=ROOT/'results/solver_correction';evidence.mkdir(parents=True,exist_ok=True)  # Preserve source, patch, compiler log and executable identity.
    url='https://www.dhondt.de/ccx_2.23.src.tar.bz2';response=requests.get(url,timeout=120);response.raise_for_status();archive_bytes=response.content  # Use the exact official source version of the verified native executable.
    with tarfile.open(fileobj=io.BytesIO(archive_bytes),mode='r:bz2') as archive:archive.extractall(folder,filter='data')  # Extract upstream source files only.
    src=next(folder.rglob('gen3dnor.f')).parent;p=src/'gen3dnor.f';original=p.read_text();(evidence/'gen3dnor_upstream.f').write_text(original)  # Preserve the unmodified upstream preprocessing routine.
    patched=original.replace('      implicit none','      implicit none\n      integer, allocatable :: requestedknots(:)',1)  # Add only a per-node bookkeeping array for requested rotational coordinates.
    code=['      allocate(requestedknots(nkold))','      requestedknots=0','      do j=1,nmpc','         index=ipompc(j)','         do while(index.ne.0)','            node=nodempc(1,index)','            if((node.gt.0).and.(node.le.nkold)) then','               if((nodempc(2,index).gt.3).or.','     &              (labmpc(j)(1:5).eq.\'RIGID\')) then','                  requestedknots(node)=1','               endif','            endif','            index=nodempc(3,index)','         enddo','      enddo']  # Scan original input constraints once, before generated MPCs enlarge the arrays.
    mark='\n'.join(line+' ! Input joint' for line in code)+'\n';patched=patched.replace('      nkold=nk','      nkold=nk\n'+mark,1)  # Comment every added Fortran line and preserve all source coefficients.
    knot='        if((requestedknots(i).eq.1).and.(nexp.eq.1).and.\n     &       (nnor.gt.0)) nexp=2\n';patched=patched.replace('        if(nexp.gt.1) then',knot+'        if(nexp.gt.1) then',1)  # Reuse upstream finite-rotation knotmpc rather than add a beam stiffness approximation.
    if patched==original or 'requestedknots=0' not in patched or 'requestedknots(i).eq.1' not in patched:raise RuntimeError('Official preprocessing source did not match the inspected patch location')  # Do not silently compile an unrelated implementation.
    p.write_text(patched);(evidence/'gen3dnor_patched.f').write_text(patched);(evidence/'preprocessor_only.patch').write_text(''.join(difflib.unified_diff(original.splitlines(True),patched.splitlines(True),fromfile='upstream/gen3dnor.f',tofile='joint-coordinates/gen3dnor.f')))  # Save a minimal independently reviewable change.
    commands=[['sudo','apt-get','update','-qq'],['sudo','apt-get','install','-y','gfortran','libspooles-dev','libarpack2-dev','liblapack-dev']]  # Use standard native compiler, factorization and eigensolver libraries.
    make=['CC=gcc','FC=gfortran','CFLAGS=-O2 -fopenmp -DARCH="Linux" -DSPOOLES -DARPACK -DMATRIXSTORAGE -I/usr/include/spooles','FFLAGS=-O2 -cpp -std=legacy -fopenmp -fallow-argument-mismatch','include Makefile.inc','OBJS=$(SCCXF:.f=.o) $(SCCXC:.c=.o)','all: ccx_joint','%.o: %.c','\t$(CC) $(CFLAGS) -c $< -o $@','%.o: %.f','\t$(FC) $(FFLAGS) -c $< -o $@','ccx_joint: ccx_2.23.o $(OBJS)','\t$(FC) -fopenmp -o $@ ccx_2.23.o $(OBJS) -lspooles -larpack -llapack -lblas -lpthread -lm']  # Enable the upstream Fortran preprocessor, including compiler-specific branches in move.f.
    (src/'Makefile.joint').write_text('\n'.join(make)+'\n')  # Preserve the exact native build configuration.
    try:  # Keep actual compiler or linker failure evidence available in concise form.
        with (evidence/'build.log').open('w') as log:  # Retain all build diagnostics, including successful compilation.
            for command in commands:subprocess.run(command,stdout=log,stderr=subprocess.STDOUT,check=True,timeout=300)  # Install only numerical build dependencies.
            subprocess.run(['make','-f','Makefile.joint','-j4'],cwd=src,stdout=log,stderr=subprocess.STDOUT,check=True,timeout=900)  # Compile unchanged upstream elements and solver routines with the stated preprocessing correction.
    finally:(evidence/'build_tail.txt').write_text((evidence/'build.log').read_text(errors='replace')[-12000:])  # Preserve an immediately readable native build result.
    exe=(src/'ccx_joint').resolve();wrapper=ROOT/'ccx';wrapper.write_text('#!/bin/sh\n# Execute official CCX 2.23 with the documented physical-joint coordinate activation.\nexec "'+str(exe)+'" "$@" # Preserve all original element and solver routines.\n');wrapper.chmod(0o755)  # Switch to the corrected implementation only after a successful native build.
    info={'upstream_url':url,'upstream_archive_sha256':hashlib.sha256(archive_bytes).hexdigest(),'original_preprocessor_sha256':hashlib.sha256(original.encode()).hexdigest(),'patched_preprocessor_sha256':hashlib.sha256(patched.encode()).hexdigest(),'executable_sha256':hashlib.sha256(exe.read_bytes()).hexdigest(),'scope':'Activate existing finite-rotation knots at input-declared rotational equations and rigid-body connectors; no physical element, material, load, stiffness or mass formula changed.'}  # Bind every native calculation to exact compiled bytes and a specific implementation scope.
    (evidence/'provenance.json').write_text(json.dumps(info,indent=2));print('NATIVE_JOINT_SOLVER',json.dumps(info),flush=True);return exe  # Report actual executable provenance, not physical-model correctness.
