from pathlib import Path  # Keep original source, exact preprocessing diff and executable provenance together.
import subprocess, requests, tarfile, io, json, hashlib, difflib  # Compile actual native code without changing engineering parameters.
ROOT=Path(__file__).parent  # Isolate the native build from all historical engineering models.
def build():  # Activate existing native rotational coordinates explicitly requested by physical connection equations.
    folder=ROOT/'runtime_joint';folder.mkdir(exist_ok=True);evidence=ROOT/'results/solver_correction';evidence.mkdir(parents=True,exist_ok=True)  # Preserve the source, patch, compiler output and executable identity.
    url='https://www.dhondt.de/ccx_2.23.src.tar.bz2';response=requests.get(url,timeout=120);response.raise_for_status();archive_bytes=response.content  # Obtain the exact official source version used in the independent element checks.
    with tarfile.open(fileobj=io.BytesIO(archive_bytes),mode='r:bz2') as archive:archive.extractall(folder,filter='data')  # Extract original source code rather than any project-specific historical solver.
    src=next(folder.rglob('gen3dnor.f')).parent;p=src/'gen3dnor.f';original=p.read_text();(evidence/'gen3dnor_upstream.f').write_text(original)  # Preserve the unmodified native preprocessing routine.
    patched=original.replace('      implicit none','      implicit none\n      integer, allocatable :: requestedknots(:)',1)  # Add only bookkeeping for native coordinates already requested by the input.
    code=['      allocate(requestedknots(nkold))','      requestedknots=0','      do j=1,nmpc','         index=ipompc(j)','         do while(index.ne.0)','            node=nodempc(1,index)','            if((node.gt.0).and.(node.le.nkold)) then','               if((nodempc(2,index).gt.3).or.','     &              (labmpc(j)(1:5).eq.\'RIGID\')) then','                  requestedknots(node)=1','               endif','            endif','            index=nodempc(3,index)','         enddo','      enddo']  # Scan original constraints before native generated MPCs expand the arrays.
    mark='\n'.join(line+' ! Input joint' for line in code)+'\n';patched=patched.replace('      nkold=nk','      nkold=nk\n'+mark,1)  # Preserve input coefficients and identify only explicitly requested physical connectors.
    knot='        if((requestedknots(i).eq.1).and.(nexp.eq.1).and.\n     &       (nnor.gt.0)) nexp=2\n';patched=patched.replace('        if(nexp.gt.1) then',knot+'        if(nexp.gt.1) then',1)  # Reuse upstream finite-rotation knotmpc instead of substituting a new stiffness formula.
    if patched==original or 'requestedknots=0' not in patched or 'requestedknots(i).eq.1' not in patched:raise RuntimeError('Official source no longer matches the inspected preprocessing patch')  # Do not silently compile an unrelated implementation.
    p.write_text(patched);(evidence/'gen3dnor_patched.f').write_text(patched);(evidence/'preprocessor_only.patch').write_text(''.join(difflib.unified_diff(original.splitlines(True),patched.splitlines(True),fromfile='upstream/gen3dnor.f',tofile='joint-coordinates/gen3dnor.f')))  # Save a minimal independently inspectable source change.
    commands=[['sudo','apt-get','update','-qq'],['sudo','apt-get','install','-y','gfortran','libspooles-dev','libarpack2-dev','liblapack-dev']]  # Use ordinary supported native compiler and numerical libraries.
    make=['CC=gcc','FC=gfortran','CFLAGS=-O2 -fcommon -fopenmp -DARCH="Linux" -DSPOOLES -DARPACK -DMATRIXSTORAGE -I/usr/include/spooles','FFLAGS=-O2 -cpp -std=legacy -fopenmp -fallow-argument-mismatch','include Makefile.inc','OBJS=$(sort $(SCCXF:.f=.o) $(SCCXC:.c=.o))','all: ccx_joint','%.o: %.c','\t$(CC) $(CFLAGS) -c $< -o $@','%.o: %.f','\t$(FC) $(FFLAGS) -c $< -o $@','ccx_library.a: $(OBJS)','\tar rcs $@ $(OBJS)','ccx_joint: ccx_2.23.o ccx_library.a','\t$(FC) -fopenmp -o $@ ccx_2.23.o ccx_library.a -lspooles -larpack -llapack -lblas -lpthread -lm']  # Use the official library-link pattern; common-symbol compatibility addresses old C globals without changing physical equations.
    (src/'Makefile.joint').write_text('\n'.join(make)+'\n');(evidence/'Makefile.joint').write_text('\n'.join(make)+'\n')  # Preserve the exact compiler and link configuration.
    try:  # Retain actual compiler or linker errors and successful build diagnostics.
        with (evidence/'build.log').open('w') as log:  # Keep complete native build output.
            for command in commands:subprocess.run(command,stdout=log,stderr=subprocess.STDOUT,check=True,timeout=300)  # Install numerical dependencies only.
            subprocess.run(['make','-f','Makefile.joint','-j4'],cwd=src,stdout=log,stderr=subprocess.STDOUT,check=True,timeout=900)  # Compile unchanged native elements, materials, nonlinear solution and eigensolver routines.
    finally:(evidence/'build_tail.txt').write_text((evidence/'build.log').read_text(errors='replace')[-6000:])  # Preserve an immediately readable native build result.
    exe=(src/'ccx_joint').resolve();wrapper=ROOT/'ccx';wrapper.write_text('#!/bin/sh\n# Execute official CCX 2.23 with explicitly requested joint-coordinate activation.\nexec "'+str(exe)+'" "$@" # Preserve the native element and solver routines.\n');wrapper.chmod(0o755)  # Use the corrected implementation only after a successful build.
    info={'upstream_url':url,'upstream_archive_sha256':hashlib.sha256(archive_bytes).hexdigest(),'original_preprocessor_sha256':hashlib.sha256(original.encode()).hexdigest(),'patched_preprocessor_sha256':hashlib.sha256(patched.encode()).hexdigest(),'executable_sha256':hashlib.sha256(exe.read_bytes()).hexdigest(),'scope':'Activate existing finite-rotation knots at input-declared rotational equations and rigid connectors; no physical element, material, load, stiffness or mass formula changed.'}  # Bind native outputs to exact executable bytes and the stated implementation boundary.
    (evidence/'provenance.json').write_text(json.dumps(info,indent=2));print('NATIVE_JOINT_SOLVER',json.dumps(info),flush=True);return exe  # Report actual compiled provenance rather than claiming the bridge model is proven correct.
