from pathlib import Path  # Keep every loaded local test separate from the bridge model and its results.
import hashlib, json, traceback, numpy as np  # Preserve exact inputs and actual successes or failures.
from scipy.spatial.transform import Rotation  # Check finite rigid-arm motion independently of the CCX connector implementation.
from physical_connectors import Deck  # Exercise the current audited physical-connector implementation without modifying it.
from physical_members import BeamLine, ordinary_gantry, BOX160, BOX50, BOX100  # Reuse the same members and joint axes as the full native model.
from run_workstate import run_native, vector_blocks  # Run the real solver and read only fresh native output.
ROOT=Path(__file__).parent; OUT=ROOT/'results/loaded_connection_diagnostics'; E=206.e9; G=9.806  # Store diagnostic evidence in the requested isolated result folder.
I160=(.16**4-.152**4)/12.; FLOOR_Y=np.r_[np.linspace(-2.67,-.85,8),np.linspace(.85,2.67,8)]; UPPER_Y=np.array([-2.45,-1.60,-.75,.75,1.60,2.45])  # Preserve section dimensions and every actual rope-clamp transverse coordinate.
SOURCE={'sha256':'0d18e3f7b009e0306fb4b9f3051b4a16d05fa24d9e966774e809b8942a4f22e1','commit':'cfbf39ef51a5bb86f13372553cee122d02df0f57','path':'catwalk-fem/mct-from-zero/source/01_设计资料与规范/猫道 - 门架索合建模型2.mct','floor_node':296,'upper_node':1168,'floor_xyz_m':[2637.0085,-2.25478355929456e-15,113.820474028094],'upper_xyz_m':[2637.0085,0.,121.741342722274],'floor_point_load_N':3180.,'upper_point_load_N':18123.,'gravity_m_s2':G}  # Freeze exact already-audited original MCT fixture facts, so this script does not depend on untracked source files or downloads.
def clamp_translations(deck,nodes):  # Define a local fixture at the actual cable-clamp points only.
    deck.fixed.update((n,d) for n in nodes for d in (1,2,3))  # Hold only the three physical translations; never prescribe a component rotation in gantry or floor-beam fixtures.
def cantilever(name):  # Provide a conventional analytic cantilever fixture used only for element/load-transfer diagnosis.
    d=Deck(name); a=d.node((0.,0.,0.),'beam'); b=d.node((0.,2.,0.),'beam'); d.beam(a,b,BOX160,'steel',8,'beam'); d.fixed.update((a,k) for k in range(1,7)); d.labels={'base':a,'tip':b}  # Fix the actual root cross-section of this standalone cantilever, never a full-bridge joint.
    return d,a,b  # Return the unchanged free tip and the independently defined local root.
def arm_case(force,direct=False):  # Test a free offset load against an equivalent free-tip force and moment.
    d,a,b=cantilever('Loaded rigid arm: '+('direct force and moment' if direct else 'actual finite offset')); offset=np.array([0.,.35,.4]); moment=float(offset[1]*force); meta={'fixture':'Standalone 2 m cantilever, root section fixed; every loaded-tip motion is solved, not prescribed.','force_z_N':force,'offset_m':offset.tolist(),'equivalent_tip_moment_x_Nm':moment,'analytic_tip_z_m':force*2.**3/(3*E*I160)+moment*2.**2/(2*E*I160),'analytic_tip_theta_x_rad':force*2.**2/(2*E*I160)+moment*2./(E*I160)}  # Use Euler-Bernoulli small-motion reference scales with the exact load lever arm.
    if direct:loads=[(b,3,force),(b,4,moment)]  # Apply the statically equivalent native end force and end moment without a connector or tip prescription.
    else:  # Exercise actual free loaded-point motion through the repaired connector.
        p=d.arm(b,d.nodes[b]+offset); rotation=d.offset_bodies[b][1]; d.labels.update({'load_point':p,'section_rotation':rotation}); loads=[(p,3,force)]; meta['rigid_motion']={'reference':b,'rotation':rotation,'point':p,'offset_m':offset.tolist()}  # Record the original physical reference and the connector's rotation coordinates for a finite-motion check.
    return d,loads,0.,meta  # Keep gravity off so the applied load alone tests virtual-work transfer.
def section_case(position,body):  # Compare a BeamLine interpolated section with direct loading at an equivalent real mesh point.
    d=Deck('Loaded beam section '+('interpolation body' if body else 'direct mesh point')); ys=np.linspace(0.,2.,9).tolist(); ys=ys if body else sorted(set(ys+[position])); line=BeamLine(d,0.,0.,ys,BOX160,'steel','beam'); a=d.node((0.,0.,0.),'beam'); tip=d.node((0.,2.,0.),'beam'); d.fixed.update((a,k) for k in range(1,7)); d.labels={'base':a,'tip':tip}; force=-100.  # Keep the same continuum cantilever, adding only a direct reference mesh station when the comparison point is off the original mesh.
    if body:  # Route the force through the exact current interpolated reference and finite body.
        ref,rot=line.section(position); point=line.attach(position,(0.,position,0.)); d.labels.update({'section':ref,'section_rotation':rot})  # Keep a coincident load point so this test isolates section interpolation from a lever-arm moment.
    else:point=d.node((0.,position,0.),'beam')  # Apply the same force directly to the physical mesh point.
    d.labels['load_point']=point; meta={'fixture':'Standalone cantilever; only its physical root section is fixed.','position_m':position,'load_z_N':force,'original_section_on_mesh':any(abs(position-y)<1.e-12 for y in np.linspace(0.,2.,17)),'mesh_stations_m':ys,'analytic_load_point_z_m':force*position**3/(3*E*I160),'analytic_tip_z_m':force*position**2*(6.-position)/(6*E*I160),'comparison_scope':'At y=1 and y=2 the base mesh is identical; at y=.93 the direct reference inserts the real load station, retaining the same geometry and material.'}  # Distinguish an exact same-mesh comparison from a continuum reference with an inserted station.
    return d,[(point,3,force)],0.,meta  # Use a force-driven test with no prescribed free displacement.
def gantry_case(gravity):  # Test all current ordinary-gantry members and connections at an original MCT station.
    xf,_,zf=SOURCE['floor_xyz_m']; xu,_,zu=SOURCE['upper_xyz_m']; center=-21.45; d=Deck('Original ordinary gantry 296/1168 loaded fixture'); lower=[(center+y,d.node((xf,center+y,zf),'floor_rope')) for y in FLOOR_Y]; upper=[(center+y,d.node((xu,center+y,zu),'upper_rope')) for y in UPPER_Y]  # Preserve the exact source x/z stations and the first catwalk's real lateral center.
    top,info=ordinary_gantry(d,xf,zf,xu,zu,center,upper,lower,'G0_296',post_axis=0,beam_cells=4); clips=[n for y,n in lower+upper]; clamp_translations(d,clips); remainder=SOURCE['upper_point_load_N']/G-d.owners[info['upper_owner']]  # Use all original ordinary-member connections and clamp only the actual 22 rope-point translations as a local fixture.
    if remainder<0:raise ValueError('Local gantry steel exceeds the original upper-source mass budget')  # Preserve a real source-mass inconsistency rather than inventing a replacement mass.
    for sign in (-1,1):top.mass_at(center+sign*1.60,zu-.50,remainder/2.)  # Retain the same two pulley/hardware gravity offsets used by the full bridge.
    ref,rot=top.section(center); point=top.attach(center,(xu,center,zu)); d.labels={'top_section':ref,'top_rotation':rot,'loaded_top_point':point}; d.labels.update({'clip_'+str(j):n for j,n in enumerate(clips)}); loads=[] if gravity else [(point,2,100.)]  # Apply either actual gravity or a transverse force at the free middle top clamp without prescribing its motion.
    meta={'source':SOURCE,'fixture':'Only translations 1/2/3 of the 16 floor and 6 upper physical rope-clamp nodes are fixed in this isolated test; all current relative hinge releases are retained.','fixture_nodes':clips,'fixed_rotation_count':sum(k>3 for n,k in d.fixed),'upper_source_mass_kg':SOURCE['upper_point_load_N']/G,'upper_native_steel_kg':d.owners[info['upper_owner']],'upper_hardware_mass_kg':remainder,'loading':'native steel and actual upper hardware gravity' if gravity else '100 N along global Y at the middle top load point, gravity disabled'}  # Do not describe the local prescribed clip translations as full-bridge boundary conditions.
    return d,loads,G if gravity else 0.,meta  # Keep gravity and transverse-force diagnostics independent.
def floor_case(gravity,large=False):  # Load the current ordinary transverse beam and its actual offset handrail masses.
    profile=BOX100 if large else BOX50; z=-.075 if large else -.05; d=Deck('Ordinary floor beam with current offset handrail mass'); row=BeamLine(d,0.,z,np.linspace(-2.89,2.89,5),profile,'floor','floor'); clips=[d.node((0.,y,0.),'floor_rope') for y in FLOOR_Y]  # Preserve the production four-cell beam, sixteen clamp coordinates and physical bearing offset.
    for y,n in zip(FLOOR_Y,clips):row.attach(float(y),d.nodes[n],existing=n)  # Use the same existing-rope-node attachment path as the bridge.
    clamp_translations(d,clips); rails=[]; tributary=3.  # Keep only physical clamp translations fixed and use the ordinary 3 m handrail tributary length.
    for sign in (-1,1):rails.append(row.mass_at(sign*2.80,1.40,10.84*tributary/2)); rails.append(row.mass_at(sign*2.80,.70,(6.68+11.84)*tributary/2))  # Preserve every current handrail mass, height and lateral lever arm without adding artificial rail stiffness.
    d.labels={'rail_'+str(j):n for j,n in enumerate(rails)}; d.labels.update({'clip_'+str(j):n for j,n in enumerate(clips)}); loads=[] if gravity else [(n,1,25.) for n in rails]; meta={'fixture':'Only translations 1/2/3 at the 16 actual floor-rope clamps are fixed; there is no artificial rotational gauge.','fixture_nodes':clips,'fixed_rotation_count':sum(k>3 for n,k in d.fixed),'profile':profile,'handrail_tributary_length_m':tributary,'handrail_total_mass_kg':(10.84+6.68+11.84)*tributary,'loading':'native beam and current offset handrail gravity' if gravity else '100 N total global X force at the four actual rail mass points; all gravity disabled','interpretation':'Any surviving rotation mechanism or load instability is preserved as a diagnostic result, not suppressed by an added support.'}  # Make the collinear-clamp fixture and its possible physical mechanisms explicit.
    return d,loads,G if gravity else 0.,meta  # Separate gravity-induced instability from pure force-driven load transfer.
def solve_case(name,factory):  # Execute one fresh real native calculation and preserve actual outputs even if another case fails.
    folder=OUT/name; folder.mkdir(parents=True,exist_ok=True); result={'name':name,'completed':False}  # Mark success only after this case actually completes.
    try:  # Preserve construction, native and parsing failures independently for each physical case.
        deck,loads,gravity,meta=factory(); deck.observation=sorted(deck.nodes); deck.save_manifest(folder/'manifest.json'); deck.write(folder/'test.inp',modes=0,gravity=gravity,loads=loads); result.update({'test_definition':meta,'input_sha256':hashlib.sha256((folder/'test.inp').read_bytes()).hexdigest(),'node_count':len(deck.nodes),'beam_count':len(deck.beams),'shell_count':len(deck.shells),'body_count':len(deck.bodies),'gravity_m_s2':gravity,'explicit_loads':loads})  # Save the actual model and force definition before native execution, without any displacement prescription at the load point.
        (folder/'definition.json').write_text(json.dumps(result,indent=2)); print('LOADED_DIAGNOSTIC_START',name,json.dumps({'nodes':len(deck.nodes),'bodies':len(deck.bodies)}),flush=True); code=run_native(folder,'test',90)  # Limit each small genuine solver attempt while retaining its full native log and invocation identity.
        dat=folder/'test.dat'; ub=vector_blocks(dat) if dat.exists() else []; fb=vector_blocks(dat,'forces') if dat.exists() else []; u=ub[-1] if ub else {}; f=fb[-1] if fb else {}; result.update({'native_exit':code,'completed':code==0 and bool(u),'displacement_block_count':len(ub),'last_displacements_by_label':{k:u.get(n) for k,n in deck.labels.items()},'last_forces_by_label':{k:f.get(n) for k,n in deck.labels.items()}})  # Preserve partial native fields as partial when the calculation fails, never as a completed equilibrium.
        (folder/'native_vectors.json').write_text(json.dumps({'displacements':u,'forces':f,'native_exit':code},indent=2))  # Keep all actually printed physical and connector coordinates for independent failure localization.
        if u:result['max_printed_vector_norm']=max(float(np.linalg.norm(v)) for v in u.values())  # This mixed-coordinate diagnostic includes rotation-reference vectors and is therefore not mislabeled as a physical displacement bound.
        for label,reference_key in (('tip','analytic_tip_z_m'),('load_point','analytic_load_point_z_m')):  # Compare only the actual measured quantities for which an analytic small-motion scale was defined.
            if reference_key in meta and label in deck.labels and deck.labels[label] in u:result[label+'_z_to_analytic_ratio']=float(u[deck.labels[label]][2]/meta[reference_key])  # Retain true shear/discretization differences without forcing numerical agreement.
        if 'rigid_motion' in meta:  # Compare a freely solved loaded arm with the independently evaluated finite rigid-body relation.
            motion=meta['rigid_motion']; needed=[motion[k] for k in ('reference','rotation','point')]  # Require actual native output for each involved physical coordinate.
            if all(n in u for n in needed):  # Avoid replacing missing or failed native coordinates by analytic predictions.
                theta=np.array(u[motion['rotation']]); measured=np.array(u[motion['point']])-np.array(u[motion['reference']]); predicted=Rotation.from_rotvec(theta).apply(motion['offset_m'])-motion['offset_m']; result['free_loaded_rigid_motion']={'native_rotation_rad':theta.tolist(),'native_relative_displacement_m':measured.tolist(),'Rodrigues_prediction_m':predicted.tolist(),'max_difference_m':float(np.max(np.abs(measured-predicted))),'theta_x_to_analytic_ratio':float(theta[0]/meta['analytic_tip_theta_x_rad'])}  # Test actual solved load transfer and its finite-arm kinematics together.
    except Exception:result['exception']=traceback.format_exc(); (folder/'execution_error.txt').write_text(result['exception'])  # Keep the real failure and continue the remaining distinct diagnostic cases.
    (folder/'result.json').write_text(json.dumps(result,indent=2)); print('LOADED_DIAGNOSTIC_RESULT',name,json.dumps(result),flush=True); return result  # Report authentic execution status and measured quantities for this one test.
def execute():  # Run the finite set of loaded physical substructures without rerunning the full bridge.
    OUT.mkdir(parents=True,exist_ok=True); cases=[('arm_force_100',lambda:arm_case(-100.)),('arm_direct_equivalent_100',lambda:arm_case(-100.,True)),('arm_force_10',lambda:arm_case(-10.))]  # Include load scaling and an independently applied equivalent end force/moment.
    for position,label in ((2.,'tip'),(1.,'mesh'),(.93,'interpolated')):  # Cover a true free end, an existing quadratic mesh node, and a section between native mesh points.
        cases.extend([('section_'+label+'_body',lambda a=position:section_case(a,True)),('section_'+label+'_direct',lambda a=position:section_case(a,False))])  # Bind each diagnostic station explicitly before executing the cases.
    cases.extend([('gantry_gravity',lambda:gantry_case(True)),('gantry_force_y',lambda:gantry_case(False)),('floor50_gravity',lambda:floor_case(True)),('floor50_force_x',lambda:floor_case(False)),('floor100_gravity',lambda:floor_case(True,True)),('floor100_force_x',lambda:floor_case(False,True))])  # Keep both production floor-member sizes and their gravity/force mechanisms visible.
    summary={'scope':'Loaded local diagnostics only; none of these fixture constraints modify the complete bridge.','source_fixture':SOURCE,'cases':{},'comparisons':{}}  # Preserve the test scope and original source identity with every incremental summary.
    for name,factory in cases:summary['cases'][name]=solve_case(name,factory); (OUT/'summary.json').write_text(json.dumps(summary,indent=2))  # Save each completed or failed case immediately so subsequent failures cannot erase it.
    pairs=[('arm_force_100','arm_direct_equivalent_100')]+[('section_'+label+'_body','section_'+label+'_direct') for label in ('tip','mesh','interpolated')]  # Compare free loaded response against the corresponding directly loaded native member.
    for left,right in pairs:  # Retain comparisons only when both actual native attempts produced the requested tip fields.
        a=summary['cases'][left]; b=summary['cases'][right]; ua=a.get('last_displacements_by_label',{}).get('tip'); ub=b.get('last_displacements_by_label',{}).get('tip')  # Read original native vectors without fitting or replacing them.
        summary['comparisons'][left+'_vs_'+right]={'both_completed':a['completed'] and b['completed'],'tip_displacement_difference_m':(np.array(ua)-np.array(ub)).tolist() if ua is not None and ub is not None else None}  # Mark differences from partial native output as incomplete rather than verified comparisons.
    summary['completed_case_count']=sum(r['completed'] for r in summary['cases'].values()); summary['failed_case_count']=len(cases)-summary['completed_case_count']; (OUT/'summary.json').write_text(json.dumps(summary,indent=2)); print('LOADED_DIAGNOSTICS_COMPLETE',json.dumps({'completed':summary['completed_case_count'],'failed':summary['failed_case_count'],'comparisons':summary['comparisons']}),flush=True); return summary  # Preserve genuine numerical failures as useful diagnosis, with an explicit case-by-case count.
ROPE_SEGMENTS={'floor':{'count':16,'center':[2637.0085,113.820474028094],'EA_N':2675842997.94008,'neighbors':[(295,295,2632.,113.914894331858,10254000.0),(296,297,2641.,113.751291215332,10253700.0)]},'upper':{'count':6,'center':[2637.0085,121.741342722274],'EA_N':1008357568.5571803,'neighbors':[(1167,1167,2628.0092999999997,121.934035247837,3115820.0),(1168,1169,2646.0092999999997,121.619369488383,3115390.0)]}}  # Freeze the exact audited MCT segments adjacent to nodes 296 and 1168; each neighbor tuple is source element, source node, x, z, aggregate initial tension.
def add_source_rope_support(deck,clips,family):  # Replace the illegal fixed dependent-node fixture with actual neighboring prestressed rope spans.
    source=ROPE_SEGMENTS[family]; anchors=[]; members=[]; deck.fixed.difference_update((n,q) for n in clips for q in (1,2,3))  # Remove only the old local clip SPCs, preserving the complete tested member and connector geometry.
    for clip in clips:  # Keep every tested rope-clamp node free and attached through its existing native rigid-body relation.
        for side,(eid,node,x,z,tension) in enumerate(source['neighbors']):  # Extend the source rope to the actual adjacent original left and right stations.
            xyz=deck.nodes[clip]+np.array([x-source['center'][0],0.,z-source['center'][1]]); anchor=deck.newnode(xyz); a,b=(anchor,clip) if side==0 else (clip,anchor); deck.axial_member(a,b,source['EA_N']/source['count'],tension/source['count'],True,'fixture_'+family,eid); anchors.append(anchor)  # Preserve each physical rope's source EA and prestress without adding an arbitrary support-spring stiffness.
            members.append({'source_element':eid,'source_neighbor_node':node,'anchor_node':anchor,'clip_node':clip,'anchor_xyz_m':xyz.tolist(),'EA_N':source['EA_N']/source['count'],'initial_tension_N':tension/source['count']})  # Retain the exact original source-to-local-fixture mapping for every support span.
    clamp_translations(deck,anchors); return anchors,members  # Fix only independent neighboring rope-end translations; all clip and member rotations remain unconstrained.
def rope_supported_case(factory,gantry=False):  # Reuse an original diagnostic component unchanged and replace only its invalid fixture boundary representation.
    deck,loads,gravity,meta=factory(); clips=list(meta['fixture_nodes']); floor_anchors,floor_members=add_source_rope_support(deck,clips[:16],'floor'); upper_anchors,upper_members=add_source_rope_support(deck,clips[16:],'upper') if gantry else ([],[])  # Preserve the same ordinary gantry or floor member, same gravity and same applied forces.
    meta.update({'previous_fixture':'Direct clip SPCs conflicted with automatically generated rigid-body dependent MPC terms; the original native201 cases remain preserved.','fixture':'Independent neighboring original-MCT rope endpoints have translations 1/2/3 fixed; tested clip nodes remain free and connect through actual source prestressed rope segments.','physical_rope_clip_nodes':clips,'fixture_nodes':floor_anchors+upper_anchors,'source_rope_spans':floor_members+upper_members,'fixed_rotation_count':sum(q>3 for n,q in deck.fixed),'support_span_mass_scope':'Support spans provide their exact original static EA/prestress/geometry; no additional segment dead load is added to the explicitly stated member/hardware gravity test.','gravity_disabled_scope':'Disabling gravity removes the test component selfweight and hardware gravity only; original support-rope prestress remains active.','fixture_version':'rope_support_v2'})  # State the source-based local truncation, its remaining initial forces, and its distinct boundary conditions without calling it a full-bridge equilibrium.
    return deck,loads,gravity,meta  # Do not change the production connector layout or suppress a real surviving rotational mechanism.
def execute_rope_supported():  # Append legal source-rope-supported cases without overwriting the nine successes or six earlier native input failures.
    OUT.mkdir(parents=True,exist_ok=True); path=OUT/'summary.json'; summary=json.loads(path.read_text()) if path.exists() else {'cases':{},'comparisons':{}}; summary['source_fixture']=SOURCE; summary['scope']='Loaded local diagnostics; original case directories retained, legal source-rope fixtures appended as rope_support_v2.'  # Preserve all earlier numerical evidence and add a separately identified diagnostic revision.
    cases=[('gantry_gravity_rope_support_v2',lambda:rope_supported_case(lambda:gantry_case(True),True)),('gantry_force_y_rope_support_v2',lambda:rope_supported_case(lambda:gantry_case(False),True)),('floor50_gravity_rope_support_v2',lambda:rope_supported_case(lambda:floor_case(True))),('floor50_force_x_rope_support_v2',lambda:rope_supported_case(lambda:floor_case(False))),('floor100_gravity_rope_support_v2',lambda:rope_supported_case(lambda:floor_case(True,True))),('floor100_force_x_rope_support_v2',lambda:rope_supported_case(lambda:floor_case(False,True)))]  # Rerun only the six previously invalid fixture families with their actual neighboring rope supports.
    for name,factory in cases:summary['cases'][name]=solve_case(name,factory); path.write_text(json.dumps(summary,indent=2))  # Preserve each new genuine native outcome immediately, including physical instability if present.
    summary['completed_case_count']=sum(r['completed'] for r in summary['cases'].values()); summary['failed_case_count']=len(summary['cases'])-summary['completed_case_count']; summary['rope_support_v2_case_count']=len(cases); path.write_text(json.dumps(summary,indent=2)); print('LOADED_ROPE_SUPPORT_DIAGNOSTICS_COMPLETE',json.dumps({name:{'completed':summary['cases'][name]['completed'],'native_exit':summary['cases'][name].get('native_exit')} for name,factory in cases}),flush=True); return summary  # Keep the count of actual new outcomes separate from the preserved old native201 evidence.
if __name__=='__main__':execute_rope_supported()  # Run only the appended legal fixtures in the next independent Actions invocation.
