from pathlib import Path  # Preserve independent member and connector tests with their actual native output.
import json, math, numpy as np  # Evaluate analytic mechanical responses without bridge target frequencies.
from scipy.spatial.transform import Rotation  # Independently compute finite three-dimensional rigid rotation.
from physical_connectors import Deck  # Use native physical sections and the explicitly documented joint coordinates.
from run_workstate import run_native, vector_blocks  # Execute a fresh native solver process and parse only its output.
ROOT=Path(__file__).parent;BOX=('BOX',(.16,.16,.004,.004,.004,.004));PIPE=('PIPE',(.076,.006))  # Use drawing-based gantry and passage member sections.
def solve(deck,name,loads=None,prescribed=None):  # Save and execute a physically defined local native test.
    folder=ROOT/'results/native_checks'/name;folder.mkdir(parents=True,exist_ok=True);deck.observation=list(deck.labels.values());deck.write(folder/'test.inp',modes=0,gravity=0.,loads=loads,prescribed=prescribed)  # Keep all test supports separate from the full-bridge model.
    code=run_native(folder,'test',180);u=vector_blocks(folder/'test.dat') if (folder/'test.dat').exists() else [];rf=vector_blocks(folder/'test.dat','forces') if (folder/'test.dat').exists() else [];result={'exit':code,'displacements':u[-1] if u else {},'forces':rf[-1] if rf else {}}  # Preserve actual current native fields, including genuine missing-output failures.
    (folder/'native_vectors.json').write_text(json.dumps(result,indent=2));return result  # Do not substitute analytic predictions for native output.
def execute_checks():  # Exercise each native member and connection type used in the global reconstruction.
    results={}  # Preserve separate physical tests and their actual solver status.
    for name,section in [('box',BOX),('pipe',PIPE)]:  # Verify actual hollow sections, not equivalent solid rectangles.
        d=Deck('Native hollow-section cantilever verification');a=d.node((0.,0.,0.));b=d.node((0.,2.,0.));d.beam(a,b,section,name,12);d.fixed.update((a,i) for i in range(1,7));d.labels={'base':a,'tip':b}  # Build a native quadratic-beam cantilever.
        native=solve(d,name,loads=[(b,3,-100.)]);I=(.16**4-.152**4)/12 if name=='box' else math.pi*(.076**4-.070**4)/4;expected=-100.*8/(3*206e9*I);value=native['displacements'].get(b,[None]*3)[2];results[name]={'native_exit':native['exit'],'native_tip_z_m':value,'Euler_Bernoulli_tip_z_m':expected,'native_to_bending_ratio':value/expected if value is not None else None}  # Retain actual shear and section-integration differences rather than force exact agreement.
    d=Deck('Finite rigid-offset compatibility verification');a=d.node((0.,0.,0.));b=d.node((0.,2.,0.));d.beam(a,b,BOX,'offset',8);d.fixed.update((a,i) for i in range(1,7));offset=np.array([.23,.17,.41]);p=d.arm(b,d.nodes[b]+offset);d.labels={'tip':b,'offset_point':p};theta=np.array([.03,.02,-.04])  # Define an actual offset point attached to a deformable beam section.
    native=solve(d,'finite_offset',prescribed=[(b,i+1,0.) for i in range(3)]+[(b,i+4,float(theta[i])) for i in range(3)]);prediction=Rotation.from_rotvec(theta).apply(offset)-offset;measured=np.array(native['displacements'][p])-np.array(native['displacements'][b]) if p in native['displacements'] and b in native['displacements'] else None  # Compare physical finite-point motion with independent Rodrigues rotation.
    results['finite_offset']={'native_exit':native['exit'],'native_relative_displacement_m':measured.tolist() if measured is not None else None,'Rodrigues_prediction_m':prediction.tolist(),'max_difference_m':float(np.max(np.abs(measured-prediction))) if measured is not None else None}  # Detect omitted lever arms or a distance-only connector.
    for axis in (0,1):  # Distinguish a free bending hinge from a pin whose released axis is along the beam.
        d=Deck('Directional relative-pin bending verification');anchor=d.node((-.2,0.,0.));master=d.node((0.,0.,0.));d.beam(anchor,master,BOX,'fixture',2);d.fixed.update((n,i) for n in (anchor,master) for i in range(1,7));slave=d.newnode((0.,0.,0.));tip=d.node((0.,2.,0.));d.beam(slave,tip,BOX,'member',10);d.pin(slave,master,axis,label='test_pin');d.labels={'tip':tip,'pin':slave}  # Constrain only relative pin coordinates and the explicitly declared local test fixture.
        if axis==1:d.fixed.add((tip,5))  # Remove the unloaded rigid spin about the beam axis in this local bending test; this gauge is not used in the full bridge.
        native=solve(d,'pin_axis_'+str(axis),prescribed=[(tip,1,0.),(tip,3,.01)]);value=native['forces'].get(tip,[None]*3)[2];results['pin_axis_'+str(axis)]={'native_exit':native['exit'],'tip_reaction_z_N':value,'tip_displacement_m':native['displacements'].get(tip),'test_only_axial_spin_gauge':axis==1}  # A free X hinge permits rigid rotation; a Y-axis pin retains Z-bending stiffness.
    d=Deck('Open HW-section shell cantilever verification');top,caps,mass=d.irow(0.,0.,np.linspace(0.,2.,13),owner='HW',tag='HW');root,rr=caps[0.];tip,tr=caps[2.];d.fixed.update((n,i) for n in (root,rr) for i in range(1,4));d.labels={'root':root,'tip':tip};native=solve(d,'open_HW_shell',loads=[(tip,3,-100.)]);I=(.17*.17**3-(.17-.007)*(.17-2*.011)**3)/12;expected=-100.*8/(3*206e9*I)  # Keep the actual web and flange shells and their free open-section warping.
    results['open_HW_shell']={'native_exit':native['exit'],'tip_z_m':native['displacements'].get(tip,[None]*3)[2],'beam_bending_scale_m':expected,'actual_shell_mass_kg':mass}  # Preserve the actual native response beside its analytic scale.
    folder=ROOT/'results/native_checks';(folder/'summary.json').write_text(json.dumps(results,indent=2));print('NATIVE_MEMBER_CONNECTION_CHECKS',json.dumps(results),flush=True);return results  # Distinguish numerical element/connection verification from the unproven target-spectrum reproduction.
