from pathlib import Path  # Preserve local-fixture modal evidence separately from production bridge results.
import csv, hashlib, json, traceback  # Record exact inputs, complete native eigenvalues and actual execution failures.
from research_floor_cases import floor_probe  # Reuse the already defined drawing-corrected rope-supported floor fixture without changing its geometry or restraints.
from run_workstate import run_native, vector_blocks, frequency_rows  # Use the same fresh native invocation and complete signed symmetric eigenvalue parser as the bridge.
ROOT=Path(__file__).parent; OUT=ROOT/'results/connection_research_modes'; REQUESTED_MODES=20  # Keep these twenty shifted local-fixture roots distinct from the requested fourteen full-bridge modes.
def parse_phases(folder,labels):  # Separate genuine static output from modal vectors before selecting any displacement field.
    dat=folder/'test.dat'; text=dat.read_text(errors='replace') if dat.exists() else ''; marker='E I G E N V A L U E'; split_at=text.find(marker)  # Locate the first actual native eigenvalue-table heading.
    static_text=text if split_at<0 else text[:split_at]; modal_text='' if split_at<0 else text[split_at:]  # Preserve the complete pre-eigenvalue static phase even when it contains several accepted load increments.
    static_file=folder/'static_phase.dat'; modal_file=folder/'modal_phase.dat'; static_file.write_text(static_text); modal_file.write_text(modal_text)  # Keep the exact phase boundary independently inspectable in the saved native text.
    static_blocks=vector_blocks(static_file); static_forces=vector_blocks(static_file,'forces'); modal_blocks=vector_blocks(modal_file); rows=frequency_rows(dat) if dat.exists() else []  # Parse static fields and all signed native roots independently rather than treating the last DAT vector block as equilibrium.
    first_static=static_blocks[0] if static_blocks else {}; last_static=static_blocks[-1] if static_blocks else {}; last_forces=static_forces[-1] if static_forces else {}; matched=bool(rows) and len(rows)==len(modal_blocks)  # Explicitly preserve the first displacement block as static; later modal vectors never overwrite it.
    vectors={'static_displacement_blocks':static_blocks,'first_static_displacements':first_static,'last_static_displacements':last_static,'static_force_blocks':static_forces,'modal_displacement_blocks_in_native_order':modal_blocks,'mode_vector_pairing_verified_by_count':matched,'mode_vectors':[{**row,'vectors':block} for row,block in zip(rows,modal_blocks)] if matched else [],'coordinate_units':'Physical-node static translations use metres; explicit rotation-reference coordinates use radians. Mode vectors have native eigenvector normalization and are not equilibrium displacements.','phase_rule':'Only DAT vector blocks before the first native eigenvalue heading are static. The first such displacement block is preserved explicitly; all later pre-heading static blocks are retained as well.'}  # Keep incomplete modal output separate when native table and vector counts do not agree.
    (folder/'native_vectors.json').write_text(json.dumps(vectors,indent=2)); (folder/'native_modes.json').write_text(json.dumps(rows,indent=2))  # Retain every actually printed vector and eigenvalue, including negative and imaginary roots.
    columns=['mode','eigenvalue','omega','frequency_hz','omega_imaginary','frequency_imaginary_hz']  # Preserve all six fields emitted by the complete symmetric native eigenvalue parser.
    with (folder/'native_frequencies.csv').open('w',newline='') as stream: writer=csv.DictWriter(stream,fieldnames=columns); writer.writeheader(); writer.writerows(rows)  # Do not sort, truncate or discard zero, negative or imaginary roots.
    return {'native_eigenvalue_count':len(rows),'native_negative_eigenvalue_count':sum(row['eigenvalue']<0 for row in rows),'native_zero_eigenvalue_count':sum(row['eigenvalue']==0 for row in rows),'native_imaginary_frequency_count':sum(row['omega_imaginary']!=0 for row in rows),'static_displacement_block_count':len(static_blocks),'static_force_block_count':len(static_forces),'modal_displacement_block_count':len(modal_blocks),'native_mode_table':rows,'mode_vector_pairing_verified_by_count':matched,'first_static_displacements_by_label':{label:first_static.get(node) for label,node in labels.items()},'last_static_displacements_by_label':{label:last_static.get(node) for label,node in labels.items()},'last_static_forces_by_label':{label:last_forces.get(node) for label,node in labels.items()},'static_modal_phase_heading_found':split_at>=0}  # Report static and modal quantities with distinct names and no borrowed fields.
def solve_case(name,large):  # Execute one unchanged direct-knot gravity fixture followed by the requested native perturbation modes.
    folder=OUT/name; folder.mkdir(parents=True,exist_ok=True); result={'case':name,'native_exit':None,'static_fields_present':False,'completed':False,'requested_native_modes':REQUESTED_MODES,'numerical_eigenvalue_shift_rad2_s2':1.,'extraction_scope':'Twenty native shift-invert roots near sigma=1 rad^2/s^2; this does not certify the globally lowest roots or the absence of unextracted negative roots.','support_scope':'Original floor_probe(direct=True, gravity=True) distant rope-end translation supports only; no additional supports, contact law, stiffness, mass or rotation locks added.'}  # Keep solver completion separate from a global stability claim.
    try:  # Preserve each actual failure and continue to the other independently defined crossbeam fixture.
        deck,loads,gravity,metadata=floor_probe(large=large,direct=True,gravity=True); deck.observation=sorted(deck.nodes); deck.save_manifest(folder/'manifest.json'); deck.write(folder/'test.inp',modes=REQUESTED_MODES,gravity=gravity,loads=loads)  # Use the same successful direct-clip model factory, adding only its modal analysis step.
        result.update({'test_definition':metadata,'input_sha256':hashlib.sha256((folder/'test.inp').read_bytes()).hexdigest(),'factory_source_sha256':hashlib.sha256((ROOT/'research_floor_cases.py').read_bytes()).hexdigest(),'node_count':len(deck.nodes),'native_beam_count':len(deck.beams),'native_shell_count':len(deck.shells),'native_axial_count':len(deck.axial),'body_count':len(deck.bodies),'gravity_m_s2':gravity,'explicit_loads':loads,'fixed_rotation_count':sum(dof>3 for node,dof in deck.fixed)})  # Publish the exact source, geometry counts and original restraint count before native execution.
        (folder/'input_sha256.txt').write_text(result['input_sha256']+'\n'); (folder/'result.json').write_text(json.dumps(result,indent=2)); print('FLOOR_MODAL_STARTED',name,result['input_sha256'],flush=True)  # Keep a truthful pending record if the runner stops during the solver invocation.
        result['native_exit']=run_native(folder,'test',180); result.update(parse_phases(folder,deck.labels)); result['static_fields_present']=result['static_displacement_block_count']>0  # run_native removes stale native outputs and saves current input/hash/invocation/log evidence.
        result['completed']=result['native_exit']==0 and result['static_fields_present'] and result['native_eigenvalue_count']==REQUESTED_MODES and result['mode_vector_pairing_verified_by_count']  # Require the requested table and vectors before describing this bounded local static-plus-modal run as complete.
        result['stability_interpretation']='At least one extracted tangent eigenvalue is negative; this indicates a locally unstable direction of this stated fixture equilibrium, subject to the preserved native completion status.' if result['native_negative_eigenvalue_count'] else 'No negative eigenvalue was printed in the extracted root set; this limited shifted extraction does not certify global stability or exclude negative roots outside that set.'  # Preserve negative-root evidence without converting a positive subset into proof of stability.
        if not result['completed']:result['stability_interpretation']='The requested local static-plus-modal run did not fully complete; preserve its printed roots and vectors as partial evidence without asserting a completed stability result.'  # Do not interpret partial solver output as a completed equilibrium eigensolution.
    except Exception: result['execution_error']=traceback.format_exc(); (folder/'execution_error.txt').write_text(result['execution_error'])  # Save the actual error without substituting old frequencies or stopping the second fixture.
    (folder/'result.json').write_text(json.dumps(result,indent=2)); print('FLOOR_MODAL_FINISHED',name,json.dumps({'native_exit':result.get('native_exit'),'completed':result['completed'],'static_blocks':result.get('static_displacement_block_count',0),'eigenvalues':result.get('native_eigenvalue_count',0),'negative_eigenvalues':result.get('native_negative_eigenvalue_count',0)}),flush=True); return result  # Save successful and failed local evidence with equal visibility.
def execute():  # Run only the two bounded direct-clip-knot gravity fixtures authorized for modal research.
    OUT.mkdir(parents=True,exist_ok=True); report={'scope':'Local drawing-corrected floor-fixture gravity equilibrium plus twenty native perturbation roots; no full-bridge model or fourteen-mode bridge result is produced.','extraction_limit':'The native sigma=1 rad^2/s^2 shift selects nearby roots, so twenty requested roots do not prove the globally lowest spectrum or complete stability.','cases':{}}  # State the scientific scope before any numerical result exists.
    for name,large in [('floor50_direct_gravity_modes',False),('floor100_direct_gravity_modes',True)]:  # Preserve the exact small and large floor_probe geometry independently.
        report['cases'][name]=solve_case(name,large); (OUT/'summary.json').write_text(json.dumps(report,indent=2))  # Persist each actual case immediately before starting the next.
    report['completed_cases']=sum(case['completed'] for case in report['cases'].values()); report['incomplete_cases']=len(report['cases'])-report['completed_cases']; (OUT/'summary.json').write_text(json.dumps(report,indent=2)); print('FLOOR_MODAL_RESEARCH_COMPLETE',json.dumps({'completed':report['completed_cases'],'incomplete':report['incomplete_cases']}),flush=True)  # A completed research workflow does not imply that either physical fixture is stable.
if __name__=='__main__':execute()  # Let the dedicated GitHub workflow perform the actual native calculations.
