from pathlib import Path  # Store this isolated diagnostic separately from the full bridge and its prior native records.
import json, math  # Preserve actual outcomes and the independently derived pendulum reference values.
from physical_connectors import Deck  # Use only the existing rigid-body serializer; this fixture contains no beam, shell or knot.
import diagnose_loaded_connections as native  # Reuse the fresh native invocation, exact input hash and original output parser.
G=9.806; MASS=100.; FORCE_X=1.  # Fix one bounded mechanical problem rather than tune a stiffness to obtain convergence.
def pendulum(above=False, gravity=True):  # Test a physical single-axis Y hinge whose only restoring effect can come from the loaded rigid body's geometry.
    d=Deck('Pure rigid-body pendulum: '+('above hinge' if above else 'below hinge')+(', gravity' if gravity else ', zero gravity')); z=1. if above else -1.; ref=d.newnode((0.,0.,0.)); rot=d.newnode((0.,0.,0.)); point=d.newnode((0.,0.,z))  # Define a fixed physical hinge, its independent rotation coordinates, and a point one metre from it.
    d.bodies.append(([point],ref,rot,'single_axis_pendulum')); d.add_mass(point,MASS); d.fixed.update((ref,q) for q in (1,2,3)); d.fixed.update(((rot,1),(rot,3)))  # Represent this fixture's actual Y-axis pin by fixing the hinge translations and its two forbidden rotations, leaving ROTY completely free.
    d.labels={'hinge':ref,'rotation':rot,'mass_point':point}; theta=-math.atan2(FORCE_X,MASS*G) if gravity else -math.pi/2.; stationary_displacement=[z*math.sin(theta),0.,z*(math.cos(theta)-1.)]  # Derive the stationary angle from dV/dtheta=-z*(mg*sin(theta)+Fx*cos(theta)), with the zero-gravity below-hinge stationary point at minus pi/2.
    meta={'fixture':'Isolated physical single-axis Y pin; its reference translations and ROTX/ROTZ are fixed, while ROTY is solved. These fixture restraints are never copied to the bridge.','native_elements':'One MASS element and one nonlinear RIGID BODY; no beam, shell, cable, rotational spring or preprocessor-created beam knot.','mass_kg':MASS,'mass_position_relative_to_hinge_m':[0.,0.,z],'force_x_N':FORCE_X,'gravity_m_s2':G if gravity else 0.,'fixed_fixture_translation_count':3,'fixed_fixture_rotation_components':['X','Z'],'free_fixture_rotation_component':'Y','potential_energy_expression':'V(theta)=m*g*z*cos(theta)-Fx*z*sin(theta)','analytic_stationary_theta_y_rad':theta,'analytic_stationary_mass_displacement_m':stationary_displacement,'analytic_stationary_potential_curvature_Nm_per_rad':-z*math.hypot(MASS*G,FORCE_X) if gravity else FORCE_X,'analytic_branch_scope':'Nearest-initial stationary angle; below-hinge gravity has positive potential curvature and above-hinge gravity has negative curvature. Newton convergence to the above-hinge branch would not establish stability.' if gravity else 'Below-hinge zero-gravity fixture has no initial restoring tangent; a finite rotation to minus pi/2 is a stationary state under the sole horizontal force, so failure from the initial vertical geometry is not by itself a solver defect.','diagnostic_question':'Can a native nonlinear rigid MPC support a stable gravity-restored pendulum under a nonzero transverse force, without any material stiffness to mask its geometric tangent?','comparison_limit':'This fixture isolates nonlinear rigid-MPC behavior and cannot prove the full bridge or either corrected floor fixture stable or unstable.'}  # Preserve the independent mechanics and the limits of each diagnostic outcome without predicting native success.
    return d,[(point,1,FORCE_X)],G if gravity else 0.,meta  # Apply the same force-driven problem to the real native solver without prescribing the free angle.
def cases():  # Return only the three requested causal controls.
    return [('pendulum_below_gravity',lambda:pendulum()),('pendulum_above_gravity',lambda:pendulum(above=True)),('pendulum_below_zero_gravity',lambda:pendulum(gravity=False))]  # Contrast stable gravity restoration, the nearest inverted stationary branch, and an initially unrestrained force direction.
def execute():  # Run the bounded native cases and preserve every actual result, including native failures.
    native.OUT=Path(__file__).parent/'results/rigid_pendulum_research'; native.OUT.mkdir(parents=True,exist_ok=True); report={'scope':'Pure nonlinear RIGID BODY pendulum diagnostic only; no bridge model or support modified.','cases':{}}  # Separate solver-formulation evidence from production model results.
    for name,factory in cases():  # Execute each independent native fixture once with the existing per-case time limit.
        result=native.solve_case(name,factory); values=result.get('last_displacements_by_label',{}); measured=values.get('rotation'); expected=result.get('test_definition',{}).get('analytic_stationary_theta_y_rad')  # Read only a rotation actually written by CCX, keeping failures and missing fields explicit.
        if result.get('completed') and measured is not None and expected is not None:result['rotation_y_difference_from_near_initial_stationary_reference_rad']=float(measured[1]-expected)  # Compare a completed actual field without selecting another periodic branch to improve agreement.
        report['cases'][name]=result; (native.OUT/name/'result.json').write_text(json.dumps(result,indent=2)); (native.OUT/'summary.json').write_text(json.dumps(report,indent=2))  # Preserve each original solver outcome and its optional analytic comparison immediately.
    report['native_completed']=sum(r.get('completed',False) for r in report['cases'].values()); report['native_failed']=len(report['cases'])-report['native_completed']; (native.OUT/'summary.json').write_text(json.dumps(report,indent=2)); print('RIGID_PENDULUM_RESEARCH_COMPLETE',json.dumps({'completed':report['native_completed'],'failed':report['native_failed']}),flush=True)  # Report execution completion separately from the success of any individual mechanical case.
if __name__=='__main__':execute()  # Launch the actual bounded diagnosis only when the dedicated workflow explicitly runs this file.
