import numpy as np  # Refine the same source-supported beam geometry without changing its section or clamp coordinates.
from physical_connectors import Deck  # Use the existing audited native finite-offset connection implementation.
from physical_members import BeamLine, BOX50  # Keep the original hollow small-beam cross-section and quadratic native members.
from diagnose_loaded_connections import FLOOR_Y, ROPE_SEGMENTS, SOURCE, G  # Reuse the immutable MCT geometry, initial forces and diagnostic gravity.
def floor_mesh_probe(section=False, refine=1, gravity=True, uniform_cells=None):  # Separate connection representation from mesh density in the corrected small-beam fixture.
    d=Deck('Corrected floor connection causal probe'); source=ROPE_SEGMENTS['floor']; half=5.520/2.; z=.05; base=sorted(set([-half,half]+FLOOR_Y.tolist())); ys=base if refine==1 else sorted(set(base+[(a+b)/2 for a,b in zip(base[:-1],base[1:])]))  # Retain the exact 17-cell mesh or bisect each of its cells into a 34-cell mesh.
    if refine not in (1,2):raise ValueError('Only the declared 17-cell and 34-cell comparisons are supported')  # Prevent an undeclared refinement rule from silently changing this bounded experiment.
    if uniform_cells not in (None,8,16) or (uniform_cells is not None and (not section or refine!=1)):raise ValueError('Uniform meshes are limited to the declared 8-cell and 16-cell section-interpolation gravity comparisons')  # Keep the added production-style refinements separate from the matched clip-node mesh comparison.
    if uniform_cells is not None:ys=np.linspace(-half,half,uniform_cells+1).tolist()  # Refine the original four uniform production cells without introducing any additional physical rope attachment.
    row=BeamLine(d,0.,z,ys,BOX50,'floor','floor'); clips=[]; support=[]; axial_facts=[]  # Create the same physical beam before adding either form of attachment representation.
    for index,y in enumerate(FLOOR_Y):  # Preserve all sixteen actual transverse carrying-rope positions in the original order.
        clip=d.node((0.,y,0.),'floor_rope')  # Keep the corrected small-beam single-point contact geometry unchanged.
        if section:row.attach(float(y),d.nodes[clip],existing=clip)  # Evaluate the original section interpolation at the exact physical clip, whether or not that position is a mesh vertex.
        else:reference=d.node((0.,y,z),'floor'); d.arm(reference,d.nodes[clip],existing=clip)  # Attach the identical physical clip directly to that native mesh knot through the existing finite arm.
        clips.append(clip)  # Preserve clip identity for source-force and displacement comparisons.
        for side_index,(eid,node,xs,zs,tension) in enumerate(source['neighbors']):  # Keep the same two original support spans for each carrying rope.
            anchor=d.newnode((xs-source['center'][0],y,zs-source['center'][1])); a,b=(anchor,clip) if side_index==0 else (clip,anchor); d.axial_member(a,b,source['EA_N']/16,tension/16,True,'fixture_rope',eid); d.fixed.update((anchor,q) for q in (1,2,3)); support.append(anchor)  # Preserve source EA, initial tension and geometry, fixing only independent remote-end translations.
            axial_facts.append({'source_element':eid,'source_node':node,'anchor_node':anchor,'clip_node':clip,'EA_N':source['EA_N']/16,'initial_tension_N':tension/16})  # Preserve the source-to-fixture map for every actual rope element.
    ref,rot=row.section(0.); load_point=row.attach(0.,(0.,0.,z)); d.labels={'middle_section':ref,'middle_rotation':rot,'load_point':load_point}; d.labels.update({'clip_'+str(i):n for i,n in enumerate(clips)})  # Keep the same central observation and force-port representation used by the preceding successful direct fixture.
    loads=[] if gravity else [(load_point,1,100.)]; meta={'source':SOURCE,'profile':BOX50,'length_m':2*half,'beam_center_above_rope_m':z,'clamp_x_offsets_m':[0.]*len(clips),'connection':'section interpolation evaluated exactly at each native clip mesh node' if section else 'direct native clip mesh knot and finite arm','mesh_stations_y_m':np.asarray(ys).tolist(),'beam_cell_count':len(ys)-1,'clip_stations_are_native_vertices':all(any(abs(float(y)-float(v))<1.e-12 for v in ys) for y in FLOOR_Y),'mesh_comparison':'17-cell direct and section cases use identical native beam mesh, material, clip coordinates and support spans; 34-cell direct case bisects the same intervals without adding physical connections.','handrail_mass_kg':0.,'handrail_tributary_m':0.,'fixture_nodes':support,'fixed_rotation_count':sum(q>3 for n,q in d.fixed),'source_rope_spans':axial_facts,'loading':'member selfweight only' if gravity else '100 N global X at the unchanged beam-center load port; component gravity disabled','support_mass_scope':'No support-span selfweight; original source initial tension remains active.','small_contact_limit':'Same single-point attachment as the preceding corrected fixture; no extra bearing, bonding, friction, spring or rotational restraint.','previous_reference_case':'floor50_corrected_gravity_direct in native run 34041763072'}  # Describe exactly which numerical choice changes and retain the successful prior-run identity without predicting these outcomes.
    if uniform_cells is not None:meta.update({'connection':'production quadratic section interpolation on a refined uniform mesh','mesh_comparison':'Refines the preceding four uniform production cells to '+str(uniform_cells)+' cells with the same section, physical clips, source support spans and loading; this is a discretization comparison, not an equivalent algebraic representation.','uniform_cell_count':uniform_cells})  # Explicitly identify the additional mesh-density question without implying native-vertex attachment at off-mesh clips.
    return d,loads,G if gravity else 0.,meta  # Return an unsolved factory result for the parent-owned native invocation and evidence recorder.
def cases():  # Supply the seven bounded mesh-versus-connection causal comparisons.
    return [('floor50_mesh17_direct_gravity',lambda:floor_mesh_probe()),('floor50_mesh17_section_gravity',lambda:floor_mesh_probe(section=True)),('floor50_mesh34_direct_gravity',lambda:floor_mesh_probe(refine=2)),('floor50_mesh17_direct_force_x',lambda:floor_mesh_probe(gravity=False)),('floor50_mesh17_section_force_x',lambda:floor_mesh_probe(section=True,gravity=False)),('floor50_mesh8_section_gravity',lambda:floor_mesh_probe(section=True,uniform_cells=8)),('floor50_mesh16_section_gravity',lambda:floor_mesh_probe(section=True,uniform_cells=16))]  # Keep the five matched-mesh/refinement controls and add only two uniform-mesh resolutions of the failing production interpolation.
