import numpy as np  # Retain exact source-rope geometry and explicit local member coordinates.
from physical_connectors import Deck  # Exercise the current native finite-offset implementation.
from physical_members import BeamLine, BOX50, BOX100  # Use the same hollow sections as the full reconstruction.
from diagnose_loaded_connections import FLOOR_Y, ROPE_SEGMENTS, SOURCE, G  # Reuse immutable original-MCT facts and the documented diagnostic gravity.
def floor_probe(large=False, direct=False, gravity=True):  # Separate corrected geometry, section interpolation and load direction in a source-rope fixture.
    d=Deck('Corrected floor connection causal probe'); source=ROPE_SEGMENTS['floor']; half=(5.772 if large else 5.520)/2.; z=.075 if large else .05; profile=BOX100 if large else BOX50; ys=sorted(set([-half,half]+FLOOR_Y.tolist())) if direct else np.linspace(-half,half,5)  # The direct alternative meshes every actual clip; its extra discretization is explicitly recorded.
    row=BeamLine(d,0.,z,ys,profile,'floor','floor'); clips=[]; support=[]; refs=[]; axial_facts=[]  # Preserve real clip nodes independently of fixed distant endpoints.
    for index,y in enumerate(FLOOR_Y):  # Follow the sixteen actual transverse carrying-rope positions.
        cx=(.075 if index%2==0 else -.075) if large else 0.; side=source['neighbors'][0 if cx<0 else 1]; dx=side[2]-source['center'][0]; dz=side[3]-source['center'][1]; clip=d.node((cx,y,cx*dz/dx),'floor_rope')  # Alternate large-beam plate centers on the actual original rope polyline; small-beam point idealization remains explicit.
        if direct:reference=d.node((0.,y,z),'floor'); d.arm(reference,d.nodes[clip],existing=clip); refs.append(reference)  # Attach directly to a true beam mesh knot, retaining the complete finite offset without a section-interpolation body.
        else:row.attach(float(y),d.nodes[clip],existing=clip)  # Reproduce the current four-cell production section interpolation.
        clips.append(clip)  # Keep the clip order available for source and reaction checks.
        for side_index,(eid,node,xs,zs,tension) in enumerate(source['neighbors']):  # Extend to fixed original neighboring rope nodes at absolute local x/z, not at translated clamp-dependent anchors.
            anchor=d.newnode((xs-source['center'][0],y,zs-source['center'][1])); a,b=(anchor,clip) if side_index==0 else (clip,anchor); d.axial_member(a,b,source['EA_N']/16,tension/16,True,'fixture_rope',eid); d.fixed.update((anchor,q) for q in (1,2,3)); support.append(anchor)  # Preserve physical EA, initial tension and geometry; only independent remote-end translations are fixed.
            axial_facts.append({'source_element':eid,'source_node':node,'anchor_node':anchor,'clip_node':clip,'EA_N':source['EA_N']/16,'initial_tension_N':tension/16})  # Retain a complete audit of each support span.
    rails=[]  # MD1-03 small beams have no high handrail masses.
    if large:  # Keep the large beam's explicitly specified three-metre local handrail tributary for comparison with previous fixtures.
        for sign in (-1,1):rails.append(row.mass_at(sign*2.80,1.40,10.84*3./2)); rails.append(row.mass_at(sign*2.80,.70,(6.68+11.84)*3./2))  # These are diagnostic tributary masses, not a claim about one complete original bridge bay.
    ref,rot=row.section(0.); load_point=row.attach(0.,(0.,0.,z)); d.labels={'middle_section':ref,'middle_rotation':rot,'load_point':load_point}; d.labels.update({'clip_'+str(i):n for i,n in enumerate(clips)}); d.labels.update({'rail_'+str(i):n for i,n in enumerate(rails)})  # Record actual finite rotation and physical point translations after a successful solve.
    loads=[] if gravity else [(load_point,1,100.)]; meta={'source':SOURCE,'profile':profile,'length_m':2*half,'beam_center_above_rope_m':z,'clamp_x_offsets_m':[float(d.nodes[n][0]) for n in clips],'connection':'direct native mesh knot and finite arm' if direct else 'production quadratic section interpolation and finite arm','mesh_stations_y_m':np.asarray(ys).tolist(),'discretization_caveat':'Direct clip-knot cases introduce extra physical beam mesh stations and cannot alone prove exact equivalence with the four-cell interpolation.','handrail_mass_kg':sum(d.mass[n] for n in rails),'handrail_tributary_m':3. if large else 0.,'fixture_nodes':support,'fixed_rotation_count':0,'source_rope_spans':axial_facts,'loading':'member and stated hardware gravity' if gravity else '100 N global X at the beam-center load port; component gravity disabled','support_mass_scope':'No support-span selfweight; original source initial tension remains active, as in the preceding legal local fixture.','small_contact_limit':'Single-point attachment retained to diagnose the saved model; no additional bearing, friction, bonding or rotational restraint is assumed.'}  # Separate numerical diagnosis from an unverified actual small-beam contact law.
    return d,loads,G if gravity else 0.,meta  # Let the native solver determine motion; prescribe no free member rotation.
def cases():  # Return only the six concrete geometry/load/interpolation discriminators.
    return [('floor50_corrected_gravity_interp',lambda:floor_probe()),('floor50_corrected_force_interp',lambda:floor_probe(gravity=False)),('floor100_corrected_gravity_interp',lambda:floor_probe(large=True)),('floor100_corrected_force_interp',lambda:floor_probe(large=True,gravity=False)),('floor50_corrected_gravity_direct',lambda:floor_probe(direct=True)),('floor100_corrected_gravity_direct',lambda:floor_probe(large=True,direct=True))]  # Preserve failures rather than tuning a model until it passes.
