from pathlib import Path  # Keep complete native inputs and outputs in the source-based reconstruction branch.
import json, math, csv, hashlib, collections, re, numpy as np  # Preserve actual geometry, original state data and auditable mass accounting.
from physical_connectors import Deck  # Use native finite-rotation section and clamp kinematics.
from physical_members import BeamLine, ordinary_gantry, passage, BOX50, BOX100  # Build the actual flexible physical member families.
from mct_workstate import expand  # Parse original MIDAS node and element groups without substituting historical model sets.
from run_workstate import run_native, vector_blocks, frequency_rows  # Execute the native solver and read actual results.
ROOT=Path(__file__).parent;CENTERS=(-21.45,21.45);FLOOR_Y=np.r_[np.linspace(-2.67,-.85,8),np.linspace(.85,2.67,8)];UPPER_Y=np.array([-2.45,-1.60,-.75,.75,1.60,2.45])  # Preserve sixteen floor-rope positions; the six upper transverse offsets are explicitly recorded as a drawing-detail interpretation.
def source_group(source,name):  # Read a named group from its actual original multiline MCT definition.
    text=' '.join(source['sections'].get('*GROUP',[])).replace('\\',' ');parts=re.split(re.escape(name)+r'\s*,',text,maxsplit=1)  # Preserve wrapped lists and accept the original padded group-name field before its comma.
    if len(parts)!=2:raise ValueError('Original MCT group missing: '+name)  # Do not silently invent a source group.
    return expand(parts[1].split(',')[0])  # Return only the named group's original node list.
class Reconstruction:  # Preserve source topology, physical member geometry and independent mass ownership.
    def __init__(self,source,cells=4,pin_axis=0,fork_axis=1):  # Define a complete model without loading target frequencies.
        self.s=source;self.d=Deck('Original MCT double catwalk: native flexible members and physical relative joints');self.cells=cells;self.pin_axis=pin_axis;self.fork_axis=fork_axis;self.mass_ledger=[];self.body_ports={};self.source_map={};self.floor_map={};self.upper_map={};self.rows={};self.upper_rows={};self.passages=[]  # Track every source and assembled object explicitly.
        self.floor_records=sorted([r for r in source['cables'] if r[1]<=728 and r[2]<=728],key=lambda r:source['nodes'][r[1]][0]);self.upper_records=sorted([r for r in source['cables'] if r[3]==2],key=lambda r:source['nodes'][r[1]][0]);self.down_records=[r for r in source['cables'] if r not in self.floor_records and r not in self.upper_records]  # Separate continuous ropes from actual down-pull elements.
        self.floor_ids=sorted({n for r in self.floor_records for n in r[1:3]},key=lambda n:source['nodes'][n][0]);self.upper_ids=sorted({n for r in self.upper_records for n in r[1:3]},key=lambda n:source['nodes'][n][0]);self.fx=np.array([source['nodes'][n][0] for n in self.floor_ids]);self.fz=np.array([source['nodes'][n][2] for n in self.floor_ids]);self.ux=np.array([source['nodes'][n][0] for n in self.upper_ids]);self.uz=np.array([source['nodes'][n][2] for n in self.upper_ids])  # Retain every original source coordinate, including anchor and saddle transition vertices.
        self.passage_ids=source_group(source,'横向通道节点');self.frame_ids=source_group(source,'钢架节点');self.gantry_pairs={r[2]:r[1] for r in source['posts']};self.passage_x={float(source['nodes'][n][0]):n for n in self.passage_ids};self.frame_x={float(source['nodes'][n][0]):n for n in self.frame_ids};self.gantry_x={float(source['nodes'][n][0]):(n,u) for n,u in self.gantry_pairs.items()}  # Preserve source-defined gantry and passage locations instead of periodic guesses.
        self.budget={n:-float(f[2])/source['g'] for n,f in source['point'].items()};self.used=collections.defaultdict(float);self.attach_counts=collections.Counter();self.original_floor_length=sum(r[6] for r in self.floor_records);self.original_upper_length=sum(r[6] for r in self.upper_records)  # Separate original concentrated and distributed permanent masses.
    def floor_node(self,deck,rope,x):  # Create a physical floor-rope point at an original or newly inserted attachment station.
        key=(deck,rope,round(float(x),9))  # Use one consistent physical cable node at each attachment.
        if key not in self.floor_map:self.floor_map[key]=self.d.node((x,CENTERS[deck]+FLOOR_Y[rope],np.interp(x,self.fx,self.fz)),'floor_rope')  # Preserve the original MCT polyline exactly, not a fitted parabola.
        return self.floor_map[key]  # Return the real rope point for source loads and clamps.
    def upper_node(self,deck,rope,x):  # Preserve each upper carrying rope independently.
        key=(deck,rope,round(float(x),9))  # Keep original upper-station geometry distinct from floor stations.
        if key not in self.upper_map:self.upper_map[key]=self.d.node((x,CENTERS[deck]+UPPER_Y[rope],np.interp(x,self.ux,self.uz)),'upper_rope')  # Retain the original upper-rope polyline and actual lateral offset.
        return self.upper_map[key]  # Return a unique physical upper-rope point.
    def floor_ports(self,deck,x):return [(CENTERS[deck]+FLOOR_Y[j],self.floor_node(deck,j,x)) for j in range(16)]  # Expose all sixteen separate lower rope clamps.
    def upper_ports(self,deck,x):return [(CENTERS[deck]+UPPER_Y[j],self.upper_node(deck,j,x)) for j in range(6)]  # Expose all six separate upper rope clamps.
    def spend(self,source_node,owner,deck=0,fraction=1.):  # Charge actual native steel mass to its corresponding original permanent-load budget.
        mass=float(self.d.owners[owner])*fraction;self.used[(deck,source_node)]+=mass;self.mass_ledger.append({'source_node':source_node,'deck':deck,'owner':owner,'steel_mass_kg':mass,'original_point_mass_kg':self.budget.get(source_node,0.)})  # Keep structural density separate from residual nonstructural mass.
    def make_members(self):  # Assemble all flexible member families and physical joints before assigning any modal classification.
        s=self.s;d=self.d  # Use the original geometry and the newly constructed native deck.
        for x,(lower,upper) in self.gantry_x.items():  # Build each source gantry once, using the correct ordinary or cross-passage family.
            if lower in self.passage_ids:continue  # Cross-passage gantries are forked supports built with their truss, not duplicated ordinary gates.
            for deck,center in enumerate(CENTERS):  # Preserve both catwalks and their separate source mass budgets.
                xu,_,zu=s['nodes'][upper];zf=s['nodes'][lower][2];tag=f'G{deck}_{lower}';top,info=ordinary_gantry(d,x,zf,xu,zu,center,self.upper_ports(deck,xu),self.floor_ports(deck,x),tag,self.pin_axis,self.cells);self.rows[(deck,round(x,9))]=('HW',info);self.upper_rows[(deck,upper)]=top;self.spend(upper,info['upper_owner'],deck);self.spend(lower,info['bottom_owner'],deck)  # Retain separate upper and lower attachments with directional hinges.
        for x,lower in sorted(self.passage_x.items()):  # Use the original twenty-one source passage stations.
            upper=self.gantry_pairs[lower];xu,_,zu=s['nodes'][upper];slope=float((np.interp(x+.01,self.fx,self.fz)-np.interp(x-.01,self.fx,self.fz))/.02);tag='P'+str(lower);obj=passage(d,x,s['nodes'][lower][2],slope,[(xu,zu)]*2,[self.upper_ports(j,xu) for j in range(2)],self.floor_ports,CENTERS,tag,self.pin_axis,self.fork_axis,33,self.cells)  # Preserve inverted-triangle members, fore/aft collector ports and forked supports.
            self.passages.append((lower,upper,obj))  # Record the complete cross-passage substructure as one physical assembly.
            for deck in range(2):self.upper_rows[(deck,upper)]=obj['tops'][deck];self.spend(upper,obj['gate_owners'][deck],deck);self.used[(deck,lower)]+=(d.owners[obj['truss_owner']]+d.owners[obj['collector_owner']])/2  # Charge the shared truss only once across both catwalks.
        big=[]  # Identify large crossbeam locations from the original concentrated-load pattern rather than a global guessed spacing.
        for n in self.floor_ids:  # Inspect actual source load locations along the floor rope.
            f=-s['point'].get(n,np.zeros(3))[2]/1000;remaining=f-(3.18 if n in self.gantry_pairs and n not in self.passage_ids else 0.)  # Remove the separately modeled ordinary gate bottom-beam load component.
            if n not in self.frame_ids and (abs(remaining-1.32)<.025 or abs(remaining-2.53)<.025 or n in self.passage_ids):big.append(float(s['nodes'][n][0]))  # Preserve source-supported beam locations, not target-spectrum tuning.
        station=set(big)|set(self.gantry_x)|set(self.frame_x)  # Keep actual gates and deformation-frame positions in the floor member map.
        for left,right in zip(sorted(big)[:-1],sorted(big)[1:]):  # Insert the small crossbeams only within contiguous source big-beam bays.
            if 3.01<right-left<12.1:station.update(float(v) for v in np.arange(left+3.,right-1.e-5,3.))  # Use the original small-beam spacing without crossing discontinuous anchor or tower transitions.
        self.floor_stations=sorted(station);self.large_floor_stations=set(big);self.rail_stations=sorted(set(big)|set(self.gantry_x)|set(self.frame_x));source_at_x={round(float(s['nodes'][n][0]),9):n for n in self.floor_ids};self.small_owners=[]  # MD1-01/02 put railing posts on large assemblies; MD1-03 small beams carry no posts, so preserve separate rail-support stations.
        for x in self.floor_stations:  # Build one actual crossbeam assembly at each intended floor member station.
            for deck,center in enumerate(CENTERS):  # Keep the two decks mechanically separate except through the real passages.
                if (deck,round(x,9)) in self.rows:continue  # Do not duplicate a gantry's actual HW bottom crossbeam at the same physical station.
                n=source_at_x.get(round(x,9));large=x in self.large_floor_stations;profile=BOX100 if large else BOX50;tag=f'F{deck}_{x:.6f}';zf=float(np.interp(x,self.fx,self.fz));tube_length=5.772 if large else 5.520;row=BeamLine(d,x,zf+(.075 if large else .05),np.linspace(center-tube_length/2,center+tube_length/2,self.cells+1),profile,tag,tag)  # MD1-02/03 give native tube lengths 5772/5520 mm; place tubes above phi50 ropes, explicitly neglecting intervening plate and mesh thickness in these center offsets.
                if n in self.frame_ids:  # Source deformation frames are handled separately as multi-point near-rigid spreaders.
                    self.small_owners.append(tag)  # Retain this narrow floor member's density within the distributed mass budget.
                elif n in self.budget and large:self.spend(n,tag,deck)  # Subtract real big-crossbeam steel from the original assembly point load.
                else:self.small_owners.append(tag)  # Small-beam steel comes from the original homogenized floor mass.
                for rope,dy in enumerate(FLOOR_Y):  # MD1-02 note 4 alternates the large-beam carrying-rope connection plates on its two longitudinal sides.
                    clamp_x=x+(.075 if rope%2==0 else -.075) if large and n not in self.frame_ids else x;node=self.floor_node(deck,rope,clamp_x);row.attach(center+dy,d.nodes[node],existing=node)  # Use actual source-polyline rope points at the alternating plate centers; the 50 versus 45 mm plate-projection discrepancy remains an explicit drawing interpretation.
                self.rows[(deck,round(x,9))]=('BEAM',row)  # Keep native flexible floor beams, not a rigid-section global approximation.
        self.make_downpull()  # Add the source down-pull system after its real transverse floor connection exists.
    def make_downpull(self):  # Preserve the MCT down-pull force and axial stiffness while distributing each equivalent element into four physical pulley-group ports.
        s=self.s;d=self.d;groups=np.array([np.mean(FLOOR_Y[i:i+4]) for i in range(0,16,4)])  # Declare the four force-spreader positions explicitly; the source 2D MCT alone does not identify their lateral offsets.
        for r in self.down_records:  # Use only the original two down-pull elements and their actual upper/lower source coordinates.
            eid,a,b,mat,EA,N,L=r;lower=a if a in (729,730) else b;upper=b if lower==a else a;xf,_,zf=s['nodes'][upper]  # Retain original tower anchorage geometry and initial axial force.
            for deck,center in enumerate(CENTERS):  # Preserve each catwalk's source-equivalent down-pull action independently.
                kind,row=self.rows[(deck,round(float(xf),9))]  # Transfer each pulley group's force through the modeled transverse floor member.
                for j,dy in enumerate(groups):  # Do not attach the entire down-pull bundle to a single arbitrary high master node.
                    y=center+dy;top=row.attach(y,(xf,y,zf));bottom=d.node((s['nodes'][lower][0],y,s['nodes'][lower][2]),'down_anchor');d.axial_member(bottom,top,EA/4,N/4,True,'downpull',eid);mass=s['weight'][mat]*s['area'][mat]*L/(4*s['g']);d.add_mass(top,mass/2);d.add_mass(bottom,mass/2);self.source_map[(deck,lower,j)]=bottom  # Preserve aggregate source tension, stiffness and gravity mass without a fabricated ground rotation.
                    d.fixed.update((bottom,q) for q in (1,2,3))  # Apply the source's actual anchored down-pull support.
        self.downpull_offsets_m=groups.tolist()  # Preserve the lateral split assumption for a later sensitivity check.
    def make_ropes_and_mass(self):  # Expand source cable segments and keep the original permanent-load mass budget exact.
        s=self.s;d=self.d;floor_uniform=s['weight'][1]*s['area'][1]*self.original_floor_length/s['g'];small_steel=sum(d.owners[n] for n in self.small_owners)/2;handrail_mu=10.84+6.68+11.84;bare_mu=16*11.989;remaining_mu=floor_uniform/self.original_floor_length-bare_mu-handrail_mu-small_steel/self.original_floor_length  # Remove physical native steel and spatial handrail inertia before assigning residual floor mass.
        if remaining_mu<0:raise ValueError('Original uniform floor budget is insufficient for explicitly assembled members')  # Diagnose duplicate physical mass rather than introduce negative inertia.
        self.floor_grid_x=np.array(sorted({round(float(x),9) for x in self.fx}|{key[2] for key in self.floor_map}));self.rail_mass_ledger=[]  # Subdivide every physical floor rope on the union of all source and attachment stations, including both sides of alternating clamps on either deck.
        for deck in range(2):  # Preserve separate source rope systems for both catwalks.
            for r in self.floor_records:  # Subdivide only where additional real attachment stations require nodes.
                eid,a,b,mat,EA,N,L=r;x1=s['nodes'][a][0];x2=s['nodes'][b][0];left_index=np.searchsorted(self.floor_grid_x,x1+1.e-8);right_index=np.searchsorted(self.floor_grid_x,x2-1.e-8);xs=[float(x1),*self.floor_grid_x[left_index:right_index].tolist(),float(x2)]  # Preserve each source segment and insert the same complete attachment grid on all sixteen ropes; never infer it from rope zero alone.
                for rope in range(16):  # Keep all sixteen physical ropes, not an equivalent single cable.
                    for left,right in zip(xs[:-1],xs[1:]):  # Preserve each original force and axial section during geometric subdivision.
                        na=self.floor_node(deck,rope,left);nb=self.floor_node(deck,rope,right);length=float(np.linalg.norm(d.nodes[nb]-d.nodes[na]));d.axial_member(na,nb,EA/16,N/16,True,'floor_rope',eid);m=length*(11.989+remaining_mu/16)  # Keep source axial prestress and explicit bare-rope plus residual floor inertia.
                        d.add_mass(na,m/2);d.add_mass(nb,m/2)  # Use a consistent lumped line-mass discretization.
                    self.source_map[(deck,a,rope)]=self.floor_node(deck,rope,x1);self.source_map[(deck,b,rope)]=self.floor_node(deck,rope,x2)  # Preserve exact source support and load-node correspondence.
            for r in self.upper_records:  # Keep all original upper-rope segments and their independent stations.
                eid,a,b,mat,EA,N,L=r  # Read the original material and work-state axial force directly.
                for rope in range(6):  # Model all six upper ropes independently.
                    na=self.upper_node(deck,rope,s['nodes'][a][0]);nb=self.upper_node(deck,rope,s['nodes'][b][0]);d.axial_member(na,nb,EA/6,N/6,True,'upper_rope',eid);m=s['weight'][2]*s['area'][2]*L/(6*s['g']);d.add_mass(na,m/2);d.add_mass(nb,m/2);self.source_map[(deck,a,rope)]=na;self.source_map[(deck,b,rope)]=nb  # Preserve the complete source upper-rope stiffness, tension and distributed mass.
        coords=np.c_[self.fx,self.fz];arc=np.r_[0.,np.cumsum(np.linalg.norm(np.diff(coords,axis=0),axis=1))];sx=np.array(self.rail_stations);rail_arc=np.interp(sx,self.fx,arc);tributary=np.diff(np.r_[0.,(rail_arc[:-1]+rail_arc[1:])/2,arc[-1]])  # Redistribute the unchanged railing line mass only to post-bearing large/HW/frame stations, using midpoint tributaries measured along the original source arc.
        for deck,center in enumerate(CENTERS):  # Place handrail and railing mesh masses at their actual lateral and vertical offsets.
            for x,length in zip(sx,tributary):  # Preserve total source line mass rather than assign arbitrary mass to each beam.
                kind,row=self.rows[(deck,round(float(x),9))];zf=float(np.interp(x,self.fx,self.fz))  # Use the local source floor elevation.
                self.rail_mass_ledger.append({'deck':deck,'station_x_m':float(x),'row_kind':kind,'owner':row.tag if kind=='BEAM' else 'HW','source_arc_tributary_m':float(length),'upper_rail_kg':float(10.84*length),'lower_rail_and_mesh_kg':float((6.68+11.84)*length)})  # Make the full railing mass redistribution auditable and show that no small beam receives high eccentric inertia.
                for sign in (-1,1):  # Preserve both physical sides of each catwalk.
                    y=center+sign*2.80  # Use the catwalk's 5.6 m usable width for railing mass placement.
                    if kind=='BEAM':row.mass_at(y,zf+1.40,10.84*length/2);row.mass_at(y,zf+.70,(6.68+11.84)*length/2)  # Include spatial inertia and gravity lever arms without adding handrail structural stiffness.
                    else:ref,rot=row['caps'][center+sign*2.95];d.lever_from_body(ref,rot,(x,y,zf+1.40),10.84*length/2);d.lever_from_body(ref,rot,(x,y,zf+.70),(6.68+11.84)*length/2)  # Attach rail mass to actual HW end connection patches at ordinary gantries.
        self.allocate_points()  # Account for original pulley, hardware, frame and passage point masses after native steel subtraction.
        for deck in range(2):  # Impose original translational support flags separately on every physical rope.
            for source_node,direction in s['fixed']:  # Preserve source longitudinal sliding at 011 supports.
                count=6 if source_node>=1001 else (4 if source_node in (729,730) else 16)  # Retain the original physical object family.
                for rope in range(count):  # Apply only the original physical support components.
                    n=self.source_map.get((deck,source_node,rope))  # Identify the exact expanded source node.
                    if n is not None:d.fixed.add((n,direction+1))  # Do not add ground rotational constraints.
        self.mass_summary={'source_one_deck_kg':sum(s['mass'].values()),'source_two_decks_kg':2*sum(s['mass'].values()),'native_steel_kg':sum(d.owners.values()),'explicit_lumped_kg':sum(d.mass.values()),'assembled_total_kg':sum(d.owners.values())+sum(d.mass.values()),'floor_residual_nonstructural_kg_per_m':remaining_mu,'railing_two_decks_kg':sum(r['upper_rail_kg']+r['lower_rail_and_mesh_kg'] for r in self.rail_mass_ledger),'railing_source_two_decks_kg':2*handrail_mu*self.original_floor_length,'mass_relative_difference':(sum(d.owners.values())+sum(d.mass.values()))/(2*sum(s['mass'].values()))-1}  # Preserve exact total and railing-subledger mass conservation independently of modal agreement.
    def allocate_points(self):  # Distribute remaining original concentrated loads without duplicating native member density.
        s=self.s;d=self.d;passage_by_node={n:obj for n,u,obj in self.passages}  # Preserve the original shared passage mass ownership.
        for deck,center in enumerate(CENTERS):  # Keep original one-deck source budgets separate before sharing a passage.
            for n,budget in self.budget.items():  # Read every original permanent point mass, including small ancillary loads.
                remaining=budget-self.used[(deck,n)]  # Remove only real native steel already charged to this exact source object.
                if remaining<-.01:raise ValueError(f'Physical steel exceeds original point-mass budget: deck={deck}, node={n}, remaining={remaining}, used={self.used[(deck,n)]}, budget={budget}')  # Expose a geometry or source-budget mismatch rather than normalize it away.
                remaining=max(remaining,0.)  # Remove only sub-gram floating-point remainder.
                if n in passage_by_node:  # Distribute the shared passage's deck, mesh and hardware mass along the real truss.
                    obj=passage_by_node[n];chord=obj['chords'][0];ys=np.linspace(-24.825,24.825,34);weights=np.ones(34);weights[[0,-1]]=.5;weights/=weights.sum()  # Preserve total mass with trapezoidal line quadrature.
                    for y,w in zip(ys,weights):chord.mass_at(float(y),chord.z+.12,remaining*float(w))  # Apply gravity and inertia along the physical passage instead of placing it all on the two floor centers.
                elif n>=1001 and (deck,n) in self.upper_rows:  # Place pulleys and gate hardware on the actual upper-beam assembly.
                    row=self.upper_rows[(deck,n)];zu=s['nodes'][n][2]  # Keep source upper-rope and floor elevations distinct.
                    for sign in (-1,1):row.mass_at(center+sign*1.60,zu-.50,remaining/2)  # Preserve symmetric pulley/hardware mass offsets without a high artificial master node.
                else:  # Retain other original point masses at their source physical rope positions.
                    count=6 if n>=1001 else (4 if n in (729,730) else 16)  # Respect the original rope or down-pull family.
                    for rope in range(count):  # Split source mass without adding or removing it.
                        target=self.source_map.get((deck,n,rope))  # Use exact source-to-model correspondence.
                        if target is not None:d.add_mass(target,remaining/count)  # Preserve original location when no more detailed source-supported offset exists.
        self.mass_ledger.extend({'source_node':n,'deck':deck,'budget_kg':budget,'native_steel_charged_kg':self.used[(deck,n)],'remaining_kg':budget-self.used[(deck,n)]} for deck in range(2) for n,budget in self.budget.items())  # Save all source-budget balances, not only favorable ones.
    def save(self,folder):  # Preserve exact model topology and physically meaningful observation operators.
        d=self.d;floor_order=self.floor_grid_x.tolist();ids=np.array([[[self.floor_map[(deck,r,round(float(x),9))] for r in range(16)] for x in floor_order] for deck in range(2)]);d.observation=list(dict.fromkeys(ids.ravel().tolist()+[n for key,n in self.upper_map.items()]))  # Read only existing assembled nodes on the complete shared grid; saving observations must never create an unconnected physical node.
        self.observe={'floor_x_m':floor_order,'floor_nodes':ids.tolist(),'centers_m':CENTERS,'source_saddle_x_m':[1536.,3836.,4555.026]};(folder/'observation.json').write_text(json.dumps(self.observe))  # Save the actual physical mode-classification mapping.
        assumptions={'upper_rope_offsets_m':UPPER_Y.tolist(),'upper_rope_offsets_status':'Transverse interpretation of raster gantry drawing, not identified by the planar MCT','ordinary_pin_axis_xyz':self.pin_axis,'passage_fork_lower_pin_axis_xyz':self.fork_axis,'passage_mounting_normal_offset_m':.4,'passage_panelization':'33 alternating truss panels over 49.65 m; module-specific bay labels remain a declared idealization','hanger_rod_diameter_m':.02,'downpull_group_offsets_m':self.downpull_offsets_m,'coincident_floor_members':'Ordinary HW gate beam replaces a coincident standalone floor crossbeam; original homogenized permanent mass is retained','deformation_frames':'Their source loads and down-pull ports are retained; detailed built-up Q500 frame plate flexibility is not yet resolved','source_scope':'Original design-institute MCT and original engineering review/drawings; no previous calculated spectrum or matrices used'}  # Explicitly preserve unresolved local details rather than claim a uniquely exact reconstruction.
        assumptions.update({'ordinary_floor_tube_lengths_m':{'small':5.520,'large':5.772},'ordinary_floor_vertical_offsets_m':{'small_above_rope_center':.050,'large_above_rope_center':.075},'ordinary_floor_elevation_interpretation':'MD1-01/03 place tubes above phi50 carrying ropes. Offsets use rope radius plus tube half-depth and explicitly neglect intervening mesh, weld and plate thickness. Large tube 5772 mm excludes closure plates; the depicted overall length is 5780 mm.','large_floor_rope_clamps':'MD1-02 note 4 and MD1-01 A-A: sixteen U-bolt connection plates alternate on the two longitudinal sides. Use x offsets +0.075/-0.075 m in rope order, with each point on its actual source polyline. The first side is an explicit orientation convention.','large_floor_clamp_dimension_uncertainty':'MD1-01 A-A depicts a 50 mm plate projection, giving a nominal 75 mm center offset from the 100 mm tube; MD1-02 material table instead lists a 45 mm plate dimension. The 75 mm offset is a declared interpretation pending resolution of this original drawing discrepancy.','small_floor_rope_contact':'MD1-03 depicts a 50 mm wide tube above the carrying rope, with no U-bolt, bonding, friction or preload specification. Its current single-point attachment is retained here; finite bearing contact remains unresolved.','railing_mass_distribution':'MD1-01/02 depict handrail posts on large beams; MD1-03 small beams have no posts. The unchanged railing line mass is assigned by original-source arc-length tributaries only to large, HW and source-frame stations. Frame rail attachment remains part of the stated source-frame idealization.','floor_rope_station_grid':'Every floor rope on both decks uses the union of original source stations and all inserted attachment x coordinates; observation mapping reads only existing cable nodes.'})  # Record source-supported corrections separately from unresolved contact, frame details and conflicting drawing dimensions.
        (folder/'railing_mass_ledger.json').write_text(json.dumps(self.rail_mass_ledger,ensure_ascii=False,indent=2))  # Preserve each actual railing support and its conserved arc-length tributary mass.
        (folder/'physical_assumptions.json').write_text(json.dumps(assumptions,ensure_ascii=False,indent=2));(folder/'mass_ledger.json').write_text(json.dumps(self.mass_ledger,ensure_ascii=False,indent=2));(folder/'mass_summary.json').write_text(json.dumps(self.mass_summary,indent=2));d.save_manifest(folder/'model_manifest.json')  # Preserve both complete counts and physical limitations alongside the native input.
def analyze(folder,reconstruction,exit_code):  # Classify actual native eigenvectors without nearest-target-frequency matching.
    dat=folder/'bridge.dat';rows=frequency_rows(dat) if dat.exists() else [];blocks=vector_blocks(dat) if dat.exists() else [];status={'native_exit':exit_code,'native_eigenvalue_count':len(rows),'native_negative_eigenvalue_count':sum(row['eigenvalue']<0. for row in rows),'native_displacement_blocks':len(blocks),'all_extracted_roots_have_vector_blocks':bool(rows) and len(blocks)>=len(rows),'mode_order':'Native extraction order, with no sign or frequency filtering; a shifted extraction does not certify the globally lowest roots.','vector_matching':'Pending actual eigenvalue and displacement blocks.','mass':reconstruction.mass_summary}  # Distinguish native execution from completion and retain negative roots without calling a shifted set the first lowest modes.
    if rows and len(blocks)>=len(rows):  # Use only native displacement fields actually written by the solver.
        status['vector_matching']='All extracted eigenvalue rows, including negative roots, paired in native order with the final equal-count displacement blocks; no sign or frequency filter applied.';status['negative_root_vector_count']=sum(row['eigenvalue']<0. for row in rows)  # Record the actual vector association rule without dropping unstable roots from modal classification.
        modes=blocks[-len(rows):];ids=np.array(reconstruction.observe['floor_nodes']);x=np.array(reconstruction.observe['floor_x_m']);U=np.array([[[[mode.get(int(n),[0.,0.,0.]) for n in station] for station in deck] for deck in ids] for mode in modes]);center=U.mean(axis=3);roll=(U[:,:,:,-1,2]-U[:,:,:,0,2])/(FLOOR_Y[-1]-FLOOR_Y[0]);main=(x>1536)&(x<3836);boundaries=[(852.,1536.),(1536.,3836.),(3836.,4555.026),(4555.026,5087.)]  # Retain both individual-deck roll and double-deck differential vertical motion.
        for k,row in enumerate(rows):  # Preserve the solver's actual numerical order, including extra or unexpected low roots.
            field=center[k];direction=np.sum(field**2,axis=(0,1));direction/=max(direction.sum(),1.e-100);a=field[0,main,2];b=field[1,main,2];cor=float(a@b/np.sqrt(max((a@a)*(b@b),1.e-100)));common=(field[0,:,2]+field[1,:,2])/2;differential=(field[1,:,2]-field[0,:,2])/2;span=np.array([np.sum(field[:,(x>lo)&(x<hi)]**2) for lo,hi in boundaries]);span/=max(span.sum(),1.e-100)  # Use physical displacement diagnostics without claiming they are exact kinetic-energy fractions.
            row.update({'direction_displacement_fraction':direction.tolist(),'span_displacement_fraction':span.tolist(),'main_deck_vertical_correlation':cor,'common_vertical_norm':float(np.linalg.norm(common)),'differential_vertical_norm':float(np.linalg.norm(differential)),'individual_roll_norm':float(np.linalg.norm(roll[k]))})  # Save sufficient information to diagnose mode identity rather than rename roots to match the target.
        np.savez_compressed(folder/'physical_modes.npz',x=x,center=center,individual_roll=roll,frequencies=np.array([r['frequency_hz'] for r in rows]),eigenvalues=np.array([r['eigenvalue'] for r in rows]),frequencies_imaginary=np.array([r.get('frequency_imaginary_hz',0.) for r in rows]))  # Preserve negative eigenvalues and imaginary frequencies beside native vectors instead of presenting unstable roots as zero-frequency rigid modes.
    (folder/'native_modes.json').write_text(json.dumps(rows,indent=2));(folder/'run_status.json').write_text(json.dumps(status,indent=2))  # Save only actual native results and a precise execution status.
    with (folder/'native_frequencies.csv').open('w',newline='') as f:  # Write a usable numerical table without fabricated missing values.
        writer=csv.writer(f);writer.writerow(['mode','frequency_Hz','eigenvalue','omega_rad_s','omega_imaginary','frequency_imaginary_hz']);writer.writerows([r['mode'],r['frequency_hz'],r['eigenvalue'],r['omega'],r.get('omega_imaginary',0.),r.get('frequency_imaginary_hz',0.)] for r in rows)  # Keep every extracted native root, including its actual imaginary-frequency fields, in native order.
    print('FULL_NATIVE_STATUS',json.dumps(status),'FIRST_NATIVE_ROOTS',json.dumps(rows[:16]),flush=True)  # Report actual calculation evidence, not a target-fit conclusion.
    return status  # Keep completion and reproduction as separate judgments.
def compute(source,state):  # Execute the complete newly assembled physical model.
    from read_drawing_dimensions import inspect  # Inspect otherwise unreadable numeric labels once, preserving their uncertainty.
    inspect();folder=ROOT/'results/full_spatial_native';folder.mkdir(parents=True,exist_ok=True);model=Reconstruction(source,cells=4,pin_axis=0,fork_axis=1)  # Declare the physical discretization and connection axes before reading any target spectrum.
    model.make_members();model.make_ropes_and_mass();model.save(folder);model.d.write(folder/'bridge.inp',modes=40,gravity=source['g']);(folder/'input_sha256.txt').write_text(hashlib.sha256((folder/'bridge.inp').read_bytes()).hexdigest())  # Preserve the complete executable model and its original-source mass ledger.
    print('FULL_MODEL_ASSEMBLED',json.dumps({'nodes':len(model.d.nodes),'native_beams':len(model.d.beams),'native_shells':len(model.d.shells),'native_cables':len(model.d.axial),'mass':model.mass_summary}),flush=True)  # Report actual assembled counts rather than intended counts.
    code=run_native(folder,'bridge',3600);return analyze(folder,model,code)  # Complete a real native static-plus-modal run and preserve any genuine failure.
