import numpy as np  # Use the same eight physical quadratic beam spans in every torsional load-transfer comparison.
from physical_connectors import Deck  # Exercise the currently audited finite rigid-arm connector without modifying its implementation.
from physical_members import BeamLine, BOX160  # Preserve the production 160 mm square hollow section and native section interpolation.
LENGTH=2.; FORCE_X=100.; TORQUE_Y=40.; OFFSET_Z=.4; ELASTIC=206.e9; POISSON=.31  # Declare actual diagnostic geometry, force, torque and the unchanged native steel constants in SI units.
def base_case(name):  # Build the common force-driven native cantilever fixture for all four comparisons.
    deck=Deck(name); line=BeamLine(deck,0.,0.,np.linspace(0.,LENGTH,9),BOX160,'steel','beam'); base=deck.node((0.,0.,0.),'beam'); tip=deck.node((0.,LENGTH,0.),'beam')  # Keep all eight B32R elements and all physical mesh coordinates identical across cases.
    deck.fixed.update((base,k) for k in range(1,7)); deck.labels={'base':base,'tip':tip}  # Fix only the actual root section of this isolated cantilever; retain every free-tip rotation.
    width=.16; thickness=.004; inertia=(width**4-(width-2.*thickness)**4)/12.; torsion_scale=thickness*(width-thickness)**3; shear=ELASTIC/(2.*(1.+POISSON))  # Provide the closed thin-wall Saint-Venant torsion scale, not an exact finite-element target or fitted stiffness.
    meta={'fixture':'Isolated 2 m straight Y-directed cantilever; only physical root translations and rotations are fixed.','profile':BOX160,'beam_count':8,'force_x_N':FORCE_X,'equivalent_tip_torque_y_Nm':TORQUE_Y,'load_offset_m':[0.,0.,OFFSET_Z],'reference_scope':'Thin-wall torsion and Euler-Bernoulli bending scales only; the principal check is native b/c/d equivalent-load response.','thin_wall_J_scale_m4':torsion_scale,'thin_wall_tip_theta_y_scale_rad':TORQUE_Y*LENGTH/(shear*torsion_scale),'Euler_Bernoulli_tip_x_scale_m':FORCE_X*LENGTH**3/(3.*ELASTIC*inertia),'previous_probe_gap':'The earlier arm force in global Z generated Mx and did not test My torsion of a beam aligned with global Y.','native_moment_scope':'Direct native My is applied using beam degree of freedom 5; rotation readout nodes carry no mass, force, spring or support.'}  # Preserve assumptions and state exactly which previously untested torque component this calculation probes.
    return deck,line,tip,meta  # Return the same physical native beam and freely solved tip for all loading paths.
def rotation_readout(deck,tip):  # Observe the native free-tip rotation through dependent, massless coordinates without adding physical stiffness.
    rotation=deck.newnode(deck.nodes[tip])  # Keep the readout separate from the physical beam expansion and any rigid body.
    for k in range(3):deck.equations.append([(rotation,k+1,1.),(tip,k+4,-1.)])  # Define readout translations as existing native section rotations; no absolute rotation is prescribed.
    deck.labels['section_rotation']=rotation; return rotation  # Interpret the resulting three printed values as radians rather than physical displacements.
def direct_case(pure_torque):  # Apply My alone or the native tip force plus its statically equivalent My.
    deck,line,tip,meta=base_case('Native tip My only' if pure_torque else 'Native tip Fx plus My'); rotation=rotation_readout(deck,tip); loads=[(tip,5,TORQUE_Y)] if pure_torque else [(tip,1,FORCE_X),(tip,5,TORQUE_Y)]  # Keep direct end moment loading independent of a rigid-arm implementation.
    deck.labels['load_point']=tip; meta.update({'loading_path':'native tip My only' if pure_torque else 'native tip Fx plus My','applied_force_x_N':0. if pure_torque else FORCE_X,'rotation_readout_node':rotation,'comparison_note':'The actual direct load point is the beam centerline; compare the tip vector and rotation with offset cases, then reconstruct the virtual offset response if required.'})  # Do not equate centerline displacement to an offset point displacement.
    return deck,loads,0.,meta  # Disable gravity so the torque component and connector virtual work are isolated.
def offset_case(section_path):  # Transfer the same Fx through a true positive-Z offset using either connector entry point.
    deck,line,tip,meta=base_case('BeamLine free-tip offset Fx' if section_path else 'Deck.arm free-tip offset Fx'); xyz=deck.nodes[tip]+np.array([0.,0.,OFFSET_Z])  # Preserve the same physical 0.4 m moment arm and therefore the same initial +40 Nm torque about Y.
    if section_path:reference,rotation=line.section(LENGTH); point=line.attach(LENGTH,xyz)  # Exercise production section interpolation at an actual free-end mesh station.
    else:reference=tip; point=deck.arm(tip,xyz); rotation=deck.offset_bodies[tip][1]  # Exercise the direct section arm with its own freely solved native rotation reference.
    deck.labels.update({'section':reference,'section_rotation':rotation,'load_point':point}); meta.update({'loading_path':'BeamLine.section(2) plus attach' if section_path else 'Deck.arm','applied_force_x_N':FORCE_X,'torsional_motion':{'reference':reference,'rotation':rotation,'point':point,'offset_m':[0.,0.,OFFSET_Z]},'comparison_note':'Compare native tip response and theta_y with direct Fx plus My; relative point motion is checked against the full Rodrigues rotation, retaining any bending rotation.'})  # Use a separate torsional-motion record to avoid the older diagnostic helper dividing by its Mx-only analytic reference.
    return deck,[(point,1,FORCE_X)],0.,meta  # Let the free point translate and rotate in genuine native nonlinear static equilibrium.
def cases():  # Return the smallest set separating native torsional behavior from the two physical load-transfer paths.
    return [('torsion_native_my40',lambda:direct_case(True)),('torsion_native_fx100_my40',lambda:direct_case(False)),('torsion_arm_fx100_z040',lambda:offset_case(False)),('torsion_section_fx100_z040',lambda:offset_case(True))]  # Preserve stable case names compatible with diagnose_loaded_connections.solve_case.
