from __future__ import annotations  # Keep annotations deterministic on the supported Python runtime.

import csv  # Read the immutable one-member UCAB3 property ledger.
import hashlib  # Bind every exact source and generated byte stream.
import json  # Publish a machine-readable isolation record.
from collections import defaultdict, deque  # Recover one complete connected bearing-rope line.
from pathlib import Path  # Resolve project artifacts independently of the invoking shell.

BASE = Path(__file__).resolve().parent.parent  # Anchor the C0-C5 reproduction project.
PARENT = BASE / "solver" / "c3_ub_frozen_tangent_diag" / "C3-UB-FT_DIAGNOSTIC_m06_b2a8f01c9864c0f7.inp"  # Select the exact C3 frozen-tangent deck for nodes and supports.
LEDGER = BASE / "artifacts" / "C3-UB-U_UCAB3_properties_f802f61e1de76560.csv"  # Select exact runtime UCAB3 properties.
OUTPUT_DIR = BASE / "solver" / "diagnostic_coupons" / "single_bearing_rope"  # Isolate the single-line modal coupon.
ARTIFACTS = BASE / "artifacts"  # Store immutable build evidence beside prior gates.
EXPECTED_PARENT_SHA256 = "b2a8f01c9864c0f72f5fe2e0aa3cce45e78a9267a560d8ce10dcfc19aa97048e"  # Freeze the parent model bytes.
EXPECTED_LEDGER_SHA256 = "f802f61e1de7656090076c99a1a4b729f6106fd5497830a8b72b83d873f7eabe"  # Freeze the UCAB3 property ledger bytes.
REQUESTED_MODES = 20  # Cover several span branches while keeping the isolation solve tiny.


class BuildError(RuntimeError):  # Represent one stable fail-closed coupon violation.
    pass  # Keep the semantic exception behavior-free.


def require(condition: bool, code: str, detail: str) -> None:  # Enforce one exact build contract.
    if not condition:  # Reject every condition not positively established.
        raise BuildError(f"{code}: {detail}")  # Surface a stable bounded diagnostic.


def sha256_file(path: Path) -> str:  # Hash a potentially large input without duplicate memory.
    digest = hashlib.sha256()  # Allocate a fresh exact-byte digest.
    with path.open("rb") as handle:  # Stream the selected file to EOF.
        for block in iter(lambda: handle.read(1024 * 1024), b""):  # Bound transient hashing memory to one MiB.
            digest.update(block)  # Fold every byte into the identity.
    return digest.hexdigest()  # Return the complete lowercase identity.


def audit_comments(path: Path) -> dict[str, object]:  # Enforce a comment on every nonempty coupon-source line.
    lines = path.read_text(encoding="utf-8").splitlines()  # Read the source exactly once.
    violations = [index for index, line in enumerate(lines, 1) if line.strip() and "#" not in line]  # Locate every uncommented nonempty line.
    require(not violations, "SOURCE_COMMENT_AUDIT_FAILED", repr(violations[:20]))  # Reject publication on any user-style violation.
    return {"path": str(path.relative_to(BASE)), "nonempty_lines": sum(bool(line.strip()) for line in lines), "violations": violations, "status": "PASS"}  # Return complete source-audit evidence.


def parse_parent() -> tuple[dict[int, tuple[float, float, float]], dict[int, set[int]]]:  # Recover exact coordinates and explicit support DOFs.
    coordinates: dict[int, tuple[float, float, float]] = {}  # Index exact frozen coordinates by dense node label.
    boundaries: dict[int, set[int]] = defaultdict(set)  # Index every explicitly constrained DOF by node.
    state = ""  # Track only NODE and BOUNDARY data grammars.
    with PARENT.open("r", encoding="utf-8") as handle:  # Stream the exact parent deck once.
        for raw in handle:  # Visit every input record in order.
            line = raw.strip()  # Normalize surrounding whitespace for parsing.
            if not line or line.startswith("**"):  # Ignore blank and comment records.
                continue  # Advance without state changes.
            if line.startswith("*"):  # Enter a new keyword grammar.
                upper = line.upper()  # Normalize keyword matching.
                state = "node" if upper.startswith("*NODE,") or upper == "*NODE" else "boundary" if upper == "*BOUNDARY" else ""  # Admit only model coordinates and the sole model boundary block.
                continue  # Do not interpret a keyword as data.
            if state == "node":  # Parse one coordinate record.
                fields = [field.strip() for field in line.split(",")]  # Split node and XYZ.
                require(len(fields) == 4, "NODE_ROW_INVALID", line)  # Require exactly three coordinates.
                coordinates[int(fields[0])] = (float(fields[1]), float(fields[2]), float(fields[3]))  # Preserve the exact coordinate triple.
            elif state == "boundary":  # Parse one zero-valued DOF range.
                fields = [int(field.strip()) for field in line.split(",")]  # Parse node and first/last DOF.
                require(len(fields) in (2, 3), "BOUNDARY_ROW_INVALID", line)  # Restrict to supported syntax.
                first = fields[1]  # Select the first constrained DOF.
                last = fields[2] if len(fields) == 3 else first  # Select the inclusive last constrained DOF.
                boundaries[fields[0]].update(range(first, last + 1))  # Preserve every individual constrained DOF.
    require(len(coordinates) == 91415, "PARENT_NODE_COUNT_MISMATCH", str(len(coordinates)))  # Bind the known C3 node cardinality.
    return coordinates, boundaries  # Return immutable geometry and support context.


def load_bearing_rows() -> list[dict[str, object]]:  # Load all lower bearing-rope UCAB3 members under exact schema checks.
    rows: list[dict[str, object]] = []  # Accumulate normalized physical member records.
    with LEDGER.open("r", encoding="utf-8", newline="") as handle:  # Decode the deterministic CSV ledger.
        reader = csv.DictReader(handle)  # Bind named columns.
        required = {"solver_eid", "source_elset", "node_i", "node_j", "EA_N", "N0_N", "mu_t_per_mm"}  # Freeze fields required by this isolation coupon.
        require(reader.fieldnames is not None and required.issubset(reader.fieldnames), "LEDGER_SCHEMA_INVALID", repr(reader.fieldnames))  # Require the exact property subset.
        for raw in reader:  # Traverse every UCAB3 member once.
            if raw["source_elset"] != "E_BEARING":  # Exclude gantry and downpull families.
                continue  # Advance to the next ledger row.
            rows.append({"solver_eid": int(raw["solver_eid"]), "node_i": int(raw["node_i"]), "node_j": int(raw["node_j"]), "EA_N": float(raw["EA_N"]), "N0_N": float(raw["N0_N"]), "mu_t_per_mm": float(raw["mu_t_per_mm"])})  # Normalize the exact physical property record.
    require(len(rows) == 68960, "BEARING_MEMBER_COUNT_MISMATCH", str(len(rows)))  # Require all thirty-two independent lower ropes.
    return rows  # Return the complete bearing family.


def select_one_line(rows: list[dict[str, object]]) -> list[dict[str, object]]:  # Recover the connected rope line containing the first solver element.
    node_to_rows: dict[int, list[int]] = defaultdict(list)  # Index member-row positions by endpoint node.
    for index, row in enumerate(rows):  # Traverse every lower-rope member.
        node_to_rows[int(row["node_i"])].append(index)  # Attach its I endpoint.
        node_to_rows[int(row["node_j"])].append(index)  # Attach its J endpoint.
    selected_rows: set[int] = set()  # Accumulate the connected member component.
    visited_nodes: set[int] = set()  # Prevent repeated graph expansion.
    queue: deque[int] = deque((int(rows[0]["node_i"]), int(rows[0]["node_j"])))  # Seed the component with the first bearing member.
    while queue:  # Traverse the complete rope chain.
        node = queue.popleft()  # Select the next connected node.
        if node in visited_nodes:  # Skip nodes already expanded.
            continue  # Advance without duplicate work.
        visited_nodes.add(node)  # Mark this node complete.
        for row_index in node_to_rows[node]:  # Visit every incident bearing member.
            if row_index in selected_rows:  # Skip members already admitted.
                continue  # Advance to the next incident member.
            selected_rows.add(row_index)  # Add the physical member once.
            row = rows[row_index]  # Resolve its two endpoints.
            queue.append(int(row["node_i"]))  # Continue through the I endpoint.
            queue.append(int(row["node_j"]))  # Continue through the J endpoint.
    selected = [rows[index] for index in sorted(selected_rows, key=lambda value: int(rows[value]["solver_eid"]))]  # Preserve deterministic parent-element order.
    selected_nodes = {int(row[key]) for row in selected for key in ("node_i", "node_j")}  # Recover the complete component node domain.
    require(len(selected) == 2155 and len(selected_nodes) == 2156, "SINGLE_LINE_CARDINALITY_MISMATCH", repr((len(selected), len(selected_nodes))))  # Require one simple chain among thirty-two equal ropes.
    return selected  # Return the exact full bearing-rope line.


def main() -> None:  # Build one target-free single-rope modal isolation coupon.
    require(PARENT.is_file() and LEDGER.is_file(), "SOURCE_INPUT_MISSING", repr((PARENT, LEDGER)))  # Require both immutable sources.
    require(sha256_file(PARENT) == EXPECTED_PARENT_SHA256, "PARENT_SHA256_MISMATCH", sha256_file(PARENT))  # Reject parent drift.
    require(sha256_file(LEDGER) == EXPECTED_LEDGER_SHA256, "LEDGER_SHA256_MISMATCH", sha256_file(LEDGER))  # Reject property drift.
    coordinates, boundaries = parse_parent()  # Recover exact frozen geometry and C1 support state.
    selected = select_one_line(load_bearing_rows())  # Select one complete independent lower rope.
    selected_nodes = sorted({int(row[key]) for row in selected for key in ("node_i", "node_j")})  # Freeze its node domain.
    node_map = {parent_node: coupon_node for coupon_node, parent_node in enumerate(selected_nodes, 1)}  # Densely renumber the isolated coupon.
    support_rows = [(node_map[parent_node], dof) for parent_node in selected_nodes for dof in sorted(boundaries.get(parent_node, set())) if 1 <= dof <= 3]  # Preserve only translational support DOFs on the selected rope.
    supported_nodes = {node for node, _ in support_rows}  # Count distinct isolated supports.
    require(len(supported_nodes) == 11 and len(support_rows) == 29, "SINGLE_LINE_SUPPORT_PATTERN_MISMATCH", repr((len(supported_nodes), len(support_rows))))  # Require the exact eleven-point C1 plus end-anchor mixed support pattern.
    lines = ["Single complete C3 bearing rope modal isolation; exact geometry, EA, N0, mu, and C1 supports; no steel, MASS, MPC, or target data.", "*USER ELEMENT, TYPE=UCAB3, NODES=2, INTEGRATION POINTS=1, MAXDOF=3", "*NODE, NSET=N_ALL"]  # Start the deterministic coupon deck.
    for parent_node in selected_nodes:  # Emit every physical rope node once.
        xyz = coordinates[parent_node]  # Resolve its exact frozen coordinate.
        lines.append(f"{node_map[parent_node]}, {xyz[0]:.15f}, {xyz[1]:.15f}, {xyz[2]:.15f}")  # Emit the dense node and exact coordinate triple.
    lines.append("*ELEMENT, TYPE=UCAB3, ELSET=E_ROPE")  # Start exact two-node connectivity.
    for coupon_eid, row in enumerate(selected, 1):  # Emit every physical member once.
        lines.append(f"{coupon_eid}, {node_map[int(row['node_i'])]}, {node_map[int(row['node_j'])]}")  # Preserve parent orientation and connectivity.
    lines.extend(("*MATERIAL, NAME=M_UCAB", "*ELASTIC", "1.0, 0.0", "*DENSITY", "1.0"))  # Supply the required metadata material unused by UCAB3.
    for coupon_eid, row in enumerate(selected, 1):  # Assign each member its exact frozen property triplet.
        lines.append(f"*ELSET, ELSET=C{coupon_eid}")  # Define one immutable element property set.
        lines.append(str(coupon_eid))  # Attach the exact coupon member.
        lines.append(f"*USER SECTION, ELSET=C{coupon_eid}, MATERIAL=M_UCAB, CONSTANTS=3")  # Start its UCAB3 property block.
        lines.append(f"{float(row['EA_N']):.12e}, {float(row['N0_N']):.12e}, {float(row['mu_t_per_mm']):.12e}")  # Keep every USER SECTION token within CalculiX's f20.0 reader while preserving twelve significant decimals.
    lines.append("*BOUNDARY")  # Start exact isolated translational supports.
    for node, dof in support_rows:  # Emit every supported component independently.
        lines.append(f"{node}, {dof}, {dof}")  # Apply the zero-valued C1/anchor constraint.
    lines.extend(("*STEP, PERTURBATION", "*FREQUENCY", str(REQUESTED_MODES), "*NODE FILE, NSET=N_ALL, OUTPUT=2D", "U", "*END STEP"))  # Request true lowest roots from the separately bound zero-shift solver.
    output_bytes = ("\n".join(lines) + "\n").encode("ascii")  # Freeze exact deterministic deck bytes.
    output_sha256 = hashlib.sha256(output_bytes).hexdigest()  # Bind the generated coupon identity.
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)  # Ensure the isolated solver directory exists.
    output_path = OUTPUT_DIR / f"single_bearing_rope_m{REQUESTED_MODES:02d}_{output_sha256[:16]}.inp"  # Address the coupon by exact content.
    require(not output_path.exists(), "OUTPUT_DECK_COLLISION", str(output_path))  # Preserve immutable earlier inputs.
    output_path.write_bytes(output_bytes)  # Publish only after topology and support gates pass.
    source_audit = audit_comments(Path(__file__).resolve())  # Bind the user-required source-comment audit.
    integrated_mass = sum(float(row["mu_t_per_mm"]) * ((sum((coordinates[int(row["node_j"])][axis] - coordinates[int(row["node_i"])][axis]) ** 2 for axis in range(3))) ** 0.5) for row in selected)  # Integrate exact line mass independently for evidence.
    report = {"schema": "catwalk.c3.single-bearing-rope-modal-probe.v1", "status": "ISOLATION_DECK_GENERATED_NOT_SOLVED", "target_access": "NONE", "claims": {"production": False, "full_c3": False, "frequency_reproduced": False}, "sources": {"parent_sha256": EXPECTED_PARENT_SHA256, "ledger_sha256": EXPECTED_LEDGER_SHA256}, "coupon": {"deck": str(output_path.relative_to(BASE)), "sha256": output_sha256, "nodes": len(selected_nodes), "elements": len(selected), "support_nodes": len(supported_nodes), "support_dofs": len(support_rows), "integrated_mass_t": integrated_mass, "modes": REQUESTED_MODES}, "omitted": ["all UCOR6 steel", "all native MASS", "all MPC equations", "other thirty-one bearing ropes", "all twelve gantry ropes", "downpull"], "solver_requirement": {"spectral_shift": 0.0}, "decision_rule": "Normal 0.01-to-1 Hz roots isolate the full-model MPC/steel assembly; 1e-4 Hz roots isolate UCAB3/property scaling.", "source": source_audit}  # Publish a target-free binary diagnosis contract.
    report_bytes = (json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode("utf-8")  # Serialize deterministic readable evidence.
    report_sha256 = hashlib.sha256(report_bytes).hexdigest()  # Bind every exact report byte.
    report_path = ARTIFACTS / f"single_bearing_rope_modal_probe_build_{report_sha256[:16]}.json"  # Address build evidence by content.
    require(not report_path.exists(), "BUILD_REPORT_COLLISION", str(report_path))  # Preserve immutable earlier evidence.
    report_path.write_bytes(report_bytes)  # Publish only after all isolation checks pass.
    print(json.dumps({"event": "SINGLE_BEARING_ROPE_MODAL_PROBE_GENERATED", "deck": str(output_path.relative_to(BASE)), "deck_sha256": output_sha256, "report": str(report_path.relative_to(BASE)), "report_sha256": report_sha256, "nodes": len(selected_nodes), "elements": len(selected), "mass_t": integrated_mass, "target_access": "NONE"}, sort_keys=True), flush=True)  # Emit concise solver handoff facts.


if __name__ == "__main__":  # Execute only when invoked as the single-rope isolation builder.
    main()  # Generate exact target-free solver input.
