from __future__ import annotations  # Enable stable type annotations.
import json  # Read and rewrite the deterministic calculation summary.
from pathlib import Path  # Resolve the isolated result path.

HERE = Path(__file__).resolve().parent  # Locate the inverse-form-finding directory.
SUMMARY = HERE / "results" / "summary.json"  # Locate the calculation summary generated by the solver.

# Absolute residual gates declared with the inverse operator. Do not replace
# them by a relative-to-stored comparison just to flip the success flag.
ABS_RECOVERED_LIMIT = 1.0e-8
ABS_STORED_LIMIT = 1.0e-4
ABS_BODY_P95_LIMIT = 5.0


def main() -> int:  # Record both the absolute residual verdict and the relative diagnostic.
    data = json.loads(SUMMARY.read_text(encoding="utf-8"))  # Read the unmodified numerical summary.
    maximum_force_error = float(data["all_tenstr_match"]["max_abs_percent"])  # Read the maximum elementwise force mismatch.
    body_p95_force_error = float(data["body_tenstr_match"]["p95_abs_percent"])  # Read the ninety-fifth-percentile body-member mismatch.
    recovered_equilibrium = float(data["equilibrium_relative_residual"])  # Read the recovered-force equilibrium residual.
    stored_equilibrium = float(data["stored_force_equilibrium_relative_residual"])  # Read the residual produced by the stored MCT mean forces under the same representation.
    positive_tension = float(data["minimum_recovered_tenstr_kN"]) > 0.0  # Verify that every recovered cable remains in tension.
    full_column_rank = int(data["equilibrium_nullity"]) == 0  # Verify that the element-force solution is unique in the declared equilibrium space.
    force_match = maximum_force_error <= 0.5 and body_p95_force_error <= 0.5  # Half-percent force match is a comparison diagnostic only.
    residual_consistency = recovered_equilibrium <= stored_equilibrium  # Recovered residual vs stored-mean residual is a comparison diagnostic only.
    relative_pass = bool(positive_tension and full_column_rank and force_match and residual_consistency)  # Keep the relative comparison as a named diagnostic.
    absolute_pass = bool(
        positive_tension
        and full_column_rank
        and recovered_equilibrium <= ABS_RECOVERED_LIMIT
        and stored_equilibrium <= ABS_STORED_LIMIT
        and body_p95_force_error <= ABS_BODY_P95_LIMIT
    )  # Restore the original absolute residual gates.
    data["success_initial_force_agreement"] = absolute_pass  # Absolute residual fail stays false; do not greenwash via relative comparison.
    data["success_relative_to_stored_mean_force"] = relative_pass  # Separate diagnostic: recovered residual <= stored residual and |Δ| p95 ≤ 0.5%.
    data["success_criterion"] = {
        "equilibrium_relative_residual_limit": ABS_RECOVERED_LIMIT,
        "stored_force_equilibrium_relative_residual_limit": ABS_STORED_LIMIT,
        "body_tenstr_p95_abs_percent_limit": ABS_BODY_P95_LIMIT,
        "require_positive_tension": True,
        "require_full_column_rank": True,
        "relative_diagnostic_all_tenstr_max_abs_percent_limit": 0.5,
        "relative_diagnostic_body_tenstr_p95_abs_percent_limit": 0.5,
    }  # Record absolute gates and the relative diagnostic thresholds separately.
    data["success_checks"] = {
        "all_tenstr_max_abs_percent": maximum_force_error,
        "body_tenstr_p95_abs_percent": body_p95_force_error,
        "positive_tension": positive_tension,
        "full_column_rank": full_column_rank,
        "recovered_equilibrium_relative_residual": recovered_equilibrium,
        "stored_force_equilibrium_relative_residual": stored_equilibrium,
        "recovered_residual_not_greater_than_stored": residual_consistency,
        "absolute_residual_gates_pass": absolute_pass,
        "relative_to_stored_diagnostic_pass": relative_pass,
    }  # Record the evaluated checks without replacing the absolute verdict.
    data["equilibrium_residual_interpretation"] = (
        "Absolute residual gates remain 1e-8 (recovered) and 1e-4 (stored). "
        "A recovered residual smaller than the stored-mean residual is a comparison diagnostic, "
        "not recovered INIFORCE, not attach TA1, and not a reason to drop the absolute gates."
    )  # Prevent residual-gate greenwash.
    SUMMARY.write_text(json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")  # Write the reviewed summary deterministically.
    print(json.dumps({"success_initial_force_agreement": absolute_pass, "success_relative_to_stored_mean_force": relative_pass, "success_checks": data["success_checks"]}, ensure_ascii=False, indent=2, sort_keys=True))  # Print the reviewed verdict into the workflow log.
    return 0  # Report successful verdict review.


if __name__ == "__main__":  # Execute only when invoked as a program.
    raise SystemExit(main())  # Return the program status to the operating system.
