#!/usr/bin/env python3
"""Gmsh/OpenCASCADE nominal component CAD, NOT an assembled tunnel specimen.

CAD units are millimetres (including the 1:10 files). CFD coordinates use metres.
No mesh cells or numerical-flow discretization are implemented here.
"""
import json
import math
from pathlib import Path
import gmsh

ROOT = Path(__file__).resolve().parents[1]
CFG = json.loads((ROOT / 'geometry/verified_dimensions.json').read_text())
OUT = ROOT / 'geometry/verified_parts'
OUT.mkdir(exist_ok=True)
gmsh.initialize()
gmsh.option.setNumber('General.Terminal', 0)
records = []


def box(x, y, z, dx, dy, dz):
    return (3, gmsh.model.occ.addBox(x, y, z, dx, dy, dz))


def create(name, scale):
    occ = gmsh.model.occ
    if name == 'carrier_array_9m_reference':
        length = 9000 * scale
        shapes = [(3, occ.addCylinder(x * scale, 0, 0, 0, 0, length, 25 * scale))
                  for x in CFG['carrier']['x']]
        expected_volume = 16 * math.pi * (25 * scale)**2 * length
        expected_bbox = [5390 * scale, 50 * scale, length]
        evidence = 'INP ET1/R1 cross-section; extrusion length is a 9m prototype reference, not the tunnel length'
    elif name in ('big_beam', 'small_beam'):
        p = CFG[name]
        b, t, l, c = [p[k] * scale for k in ('outer', 'thickness', 'tube_length', 'end_cap')]
        total = l + 2 * c
        outer = box(-total / 2, -b / 2, -b / 2, total, b, b)
        cavity = box(-l / 2, -b / 2 + t, -b / 2 + t, l, b - 2 * t, b - 2 * t)
        shapes, _ = occ.cut([outer], [cavity])
        expected_volume = total * b**2 - l * (b - 2 * t)**2
        expected_bbox = [total, b, b]
        evidence = p['source'] + '; nominal sharp corners; end caps included; closed internal cavity is not exterior CFD fluid'
    elif name == 'timber':
        p = CFG[name]
        sizes = [p[k] * scale for k in ('transverse_length', 'vertical_height', 'axial_width')]
        shapes = [box(0, 0, 0, *sizes)]
        expected_volume = math.prod(sizes)
        expected_bbox = sizes
        evidence = p['source'] + '; component only, vertical assembly coordinate and axial phase unresolved'
    else:
        p = CFG['post']
        b, t = p['leg'] * scale, p['thickness'] * scale
        l = p['component_length' if name == 'post_angle' else 'connector_length'] * scale
        shapes, _ = occ.fuse([box(0, 0, 0, b, l, t)], [box(0, 0, 0, t, l, b)])
        expected_volume = (2 * b * t - t * t) * l
        expected_bbox = [b, l, b]
        evidence = p['source'] + '; holes, local fillets, and fasteners not included in nominal catalogue part'
    occ.synchronize()
    return shapes, expected_volume, expected_bbox, evidence


for scale in (1.0, 0.1):
    for name in ('carrier_array_9m_reference', 'big_beam', 'small_beam', 'timber', 'post_angle', 'connector_angle'):
        label = name + ('_prototype_mm' if scale == 1 else '_scale_1to10_mm')
        gmsh.model.add(label)
        shapes, expected_volume, expected_bbox, evidence = create(name, scale)
        occ = gmsh.model.occ
        actual_volume = sum(occ.getMass(*shape) for shape in shapes)
        bboxes = [gmsh.model.getBoundingBox(*shape) for shape in shapes]
        extent = [max(b[i + 3] for b in bboxes) - min(b[i] for b in bboxes) for i in range(3)]
        assert math.isclose(actual_volume, expected_volume, rel_tol=1e-9), label
        assert all(math.isclose(a, b, abs_tol=3e-6) for a, b in zip(extent, expected_bbox)), (label, extent, expected_bbox)
        gmsh.write(str(OUT / (label + '.step')))
        if scale == 0.1:
            # Surface triangulation for review is generated by Gmsh, not by our plotting code.
            gmsh.option.setNumber('Mesh.MeshSizeMin', .5)
            gmsh.option.setNumber('Mesh.MeshSizeMax', 20)
            gmsh.option.setNumber('Mesh.MeshSizeFromCurvature', 16)
            gmsh.model.mesh.generate(2)
            gmsh.write(str(OUT / (label + '.stl')))
        records.append(dict(name=label, part=name, scale=scale, CAD_unit='mm',
                            solid_count=len(shapes), measured_bbox_mm=extent,
                            expected_bbox_mm=expected_bbox,
                            measured_material_volume_mm3=actual_volume,
                            expected_material_volume_mm3=expected_volume,
                            dimensional_checks_passed=True, source=evidence,
                            status='NOMINAL_COMPONENT_ONLY_NOT_ASSEMBLED_OR_TUNNEL_VALIDATED'))
        gmsh.model.remove()
gmsh.finalize()
(OUT / 'cad_checks.json').write_text(json.dumps(records, ensure_ascii=False, indent=2))
print(json.dumps({'component_variants': len(records), 'all_dimensional_checks_passed': True,
                  'assembled_specimen_validated': False}))
