#!/usr/bin/env python3
"""Geometry/preprocessing only. All cells are generated by Gmsh's mesher."""
import argparse, json, math, hashlib
from pathlib import Path
import gmsh
import numpy as np

p=argparse.ArgumentParser()
p.add_argument('--out',required=True)
p.add_argument('--model',default='geometry/model.json',help='Independent geometry configuration, in SI metres')
p.add_argument('--factor',type=float,default=1)
p.add_argument('--screen-height',type=float)
p.add_argument('--domain-factor',type=float,default=1)
p.add_argument('--boundary-layer',action='store_true')
a=p.parse_args()
root=Path(__file__).resolve().parents[1]
model_path=(root/a.model).resolve()
cfg=json.loads(model_path.read_text())
cfg['model_input_sha256']=hashlib.sha256(model_path.read_bytes()).hexdigest()
scale_ratio=cfg['scale']/.1
out=Path(a.out)
if (out/'mesh.msh').exists():raise RuntimeError('Refusing to overwrite a generated mesh; choose a new --out')
out.mkdir(parents=True,exist_ok=True)
if a.screen_height is not None: cfg['screen_height']=a.screen_height
gmsh.initialize();gmsh.model.add('catwalk_equal_open_area_2d')
occ=gmsh.model.occ
shapes=[];members=[]
def circle(x,y,d,group):
    shapes.append((2,occ.addDisk(x,y,0,d/2,d/2)))
    members.append(dict(x=x,y=y,diameter=d,group=group))

# Coordinates are supplied in SI metres by each independently audited model.
# Do not silently reuse the first bridge's 16-rope INP for other drawings.
assert cfg['carrier_x'] and len(set(cfg['carrier_x']))==len(cfg['carrier_x'])
for val in cfg['carrier_x']:circle(val,0,cfg['carrier_diameter'],'carrier')
pitch=cfg['equivalent_pitch']
n=round(cfg['B_geometry']/pitch)
floor_pitch=cfg['B_geometry']/n
for x in np.linspace(-cfg['B_geometry']/2+floor_pitch/2,cfg['B_geometry']/2-floor_pitch/2,n):
    if cfg.get('timber_replaces_net') and any(tx<=x<=tx+tw for tx,ty,tw,th in cfg.get('timber_sections',[])):
        continue
    beta=cfg['coarse_floor_open_area']
    group='floor_coarse_equivalent'
    if cfg.get('fine_strip_inner_x',.08*scale_ratio)<=abs(x)<=cfg.get('fine_strip_outer_x',.28*scale_ratio):
        beta*=cfg['fine_floor_open_area'];group='floor_combined_equivalent'
    circle(float(x),cfg['floor_combined_y'],floor_pitch*(1-beta),group)
for side in [-1,1]:
    h=cfg['screen_height']; nside=round(h/pitch); actual_pitch=h/nside
    for y in np.linspace(actual_pitch/2,h-actual_pitch/2,nside):
        # Avoid geometric overlap with explicit handrail: trim screen circle if necessary.
        d=actual_pitch*(1-cfg['side_open_area'])
        if all(abs(y-ry) > (d+rd)/2+.0001*scale_ratio for ry,rd in cfg['handrails']):
            circle(side*cfg['B_geometry']/2,float(y),d,'side_equivalent')
    for y,d in cfg['handrails']: circle(side*cfg['B_geometry']/2,y,d,'handrail')

x0,x1,y0,y1=[v*a.domain_factor for v in cfg['domain']]
for timber in cfg.get('timber_sections',[]):
    x,y,w,h=timber
    shapes.append((2,occ.addRectangle(x,y,0,w,h)))
    members.append(dict(x=x,y=y,width=w,height=h,shape='rectangle',group='timber'))
if cfg.get('timber_sections'):
    # OCC resolves any net/wood intersections before Gmsh generates the mesh.
    shapes,_=occ.fuse(shapes[:1],shapes[1:])
rect=occ.addRectangle(x0,y0,0,x1-x0,y1-y0)
fluid,_=occ.cut([(2,rect)],shapes)
occ.synchronize();assert len(fluid)==1
base=fluid[0][1]
curves=gmsh.model.getBoundary(fluid,oriented=False)
obstacle=[]
for dim,tag in curves:
    b=gmsh.model.getBoundingBox(dim,tag)
    if b[0]>x0+1e-5 and b[3]<x1-1e-5 and b[1]>y0+1e-5 and b[4]<y1-1e-5: obstacle.append(tag)
if a.boundary_layer: cfg['span_2d']=.001*scale_ratio
dz=cfg['span_2d']
ext=occ.extrude(fluid,0,0,dz,numElements=[1],recombine=True)
occ.synchronize()
vols=[t for d,t in ext if d==3]
gmsh.model.addPhysicalGroup(3,vols,1);gmsh.model.setPhysicalName(3,1,'fluid')
groups={'frontAndBack':[],'inlet':[],'outlet':[],'farfield':[],'body':[]}
for d,t in gmsh.model.getBoundary([(3,v) for v in vols],oriented=False):
    b=gmsh.model.getBoundingBox(d,t)
    if abs(b[5]-b[2])<1e-6: name='frontAndBack'
    elif abs(b[0]-x0)<1e-6 and abs(b[3]-x0)<1e-6: name='inlet'
    elif abs(b[0]-x1)<1e-6 and abs(b[3]-x1)<1e-6: name='outlet'
    elif (abs(b[1]-y0)<1e-6 and abs(b[4]-y0)<1e-6) or (abs(b[1]-y1)<1e-6 and abs(b[4]-y1)<1e-6): name='farfield'
    else: name='body'
    groups[name].append(t)
for j,(name,tags) in enumerate(groups.items(),2):
    assert tags, name
    gmsh.model.addPhysicalGroup(2,tags,j);gmsh.model.setPhysicalName(2,j,name)
f=gmsh.model.mesh.field
f.add('Distance',1);f.setNumbers(1,'CurvesList',obstacle);f.setNumber(1,'NNodesByEdge',40)
f.add('Threshold',2);f.setNumber(2,'InField',1)
for k,v in {'SizeMin':.00028*a.factor,'SizeMax':.012*a.factor,'DistMin':.001,'DistMax':.05}.items():f.setNumber(2,k,v)
f.add('Threshold',3);f.setNumber(3,'InField',1)
for k,v in {'SizeMin':.012*a.factor,'SizeMax':.2*a.factor,'DistMin':.06,'DistMax':.65}.items():f.setNumber(3,k,v)
# Max of the two thresholds keeps near-wall resolution without a fine entire domain.
f.add('Max',4);f.setNumbers(4,'FieldsList',[2,3])
# A single distance threshold with extended reach is simpler and avoids a near-wall size floor.
f.add('MathEval',5)
f.setString(5,'F',f'Min({.2*scale_ratio}*{a.factor}, {a.factor}*({.00028*scale_ratio} + 0.18*F1))')
f.setAsBackgroundMesh(5)
if a.boundary_layer:
    f.add('BoundaryLayer',6);f.setNumbers(6,'EdgesList',obstacle)
    f.setNumber(6,'hwall_n',.000025*a.factor*scale_ratio)
    f.setNumber(6,'thickness',.00005*scale_ratio)
    f.setNumber(6,'ratio',1.2);f.setNumber(6,'Quads',1)
    f.setAsBoundaryLayer(6)
gmsh.option.setNumber('Mesh.MeshSizeExtendFromBoundary',0)
gmsh.option.setNumber('Mesh.MeshSizeFromPoints',0)
gmsh.option.setNumber('Mesh.MeshSizeFromCurvature',16/a.factor)
gmsh.option.setNumber('Mesh.Algorithm',6)
gmsh.option.setNumber('Mesh.MshFileVersion',2.2)
gmsh.option.setNumber('General.NumThreads',1)
gmsh.model.mesh.generate(3)
gmsh.write(str(out/'mesh.msh'))
gmsh.write(str(out/'geometry.brep'))
cfg.update(mesh_factor=a.factor,domain_factor=a.domain_factor,boundary_layer=a.boundary_layer,boundary_layer_first_spacing=(.000025*a.factor*scale_ratio if a.boundary_layer else None),boundary_layer_thickness=(.00005*scale_ratio if a.boundary_layer else None),wall_treatment=('lowRe' if a.boundary_layer else 'Spalding'),members=members,physical_surface_counts={k:len(v) for k,v in groups.items()},actual_floor_pitch=floor_pitch)
(out/'geometry.json').write_text(json.dumps(cfg,indent=2))
gmsh.finalize()
